/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 15/07/2012 3:36:22 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will NOT be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Data.SqlClient;
using System.Text;

using HealthStop.Business.Framework;

namespace HealthStop.Business
{
	/// <summary>
	/// This object represents the properties and methods of a AllowedStore.
	/// </summary>
	public partial class AllowedStore : EntityBase
	{
          public static AllowedStore GetAllowedStoreByCustomerSupplier(int customerID, int supplierID)
          {
               List<SqlParameter> parameters = new List<SqlParameter>();

               parameters.Add(new SqlParameter("@customer_id", customerID));
               parameters.Add(new SqlParameter("@supplier_id", supplierID));

               string where = "where customer_id = @customer_id and supplier_id = @supplier_id";

               EntityList<AllowedStore> permissions = AllowedStore.GetAllowedStores(where, parameters);

               if (permissions.Count > 0)
               {
                    return permissions[0];
               }
               else
               {
                    return null;
               }
          }

          public static List<Company> GetSuppliers(int customerID)
          {
               List<SqlParameter> parameters = new List<SqlParameter>();

               parameters.Add(new SqlParameter("@customer_id", customerID));
               
               string where = "where customer_id = @customer_id";

               EntityList<AllowedStore> permissions = AllowedStore.GetAllowedStores(where, parameters);

               List<Company> suppliers = new List<Company>();

               foreach (var permission in permissions)
               {
                    suppliers.Add(permission.supplier_);
               }

               return suppliers;
          }

          public static List<Company> GetCustomers(int supplierID)
          {
               List<SqlParameter> parameters = new List<SqlParameter>();

               parameters.Add(new SqlParameter("@supplier_id", supplierID));

               string where = "where supplier_id = @supplier_id";

               EntityList<AllowedStore> permissions = AllowedStore.GetAllowedStores(where, parameters);

               List<Company> customers = new List<Company>();

               foreach (var permission in permissions)
               {
                    customers.Add(permission.customer_);
               }

               return customers;
          }
	}
}
