/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 10/08/2012 7:49:00 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;

using HealthStop.Business.Framework;


namespace HealthStop.Business
{
	/// <summary>
	/// This object represents the properties and methods of a Invoice.
	/// </summary>
	[Serializable()]
	[DebuggerDisplay("invoice_id: {invoice_id}")]
	public partial class Invoice
	{
		#region Public Properties
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private int _invoice_id = int.MinValue;
		/// <summary>
		/// invoice_id
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(true, true, false)]
		public int invoice_id
		{
			[DebuggerStepThrough()]
			get { return this._invoice_id; }
			protected set 
			{
				if (this._invoice_id != value) 
				{
					this._invoice_id = value;
					this.IsDirty = true;	
					OnPropertyChanged("invoice_id");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private int _customer_id = int.MinValue;
		/// <summary>
		/// customer_id
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, false)]
		public int customer_id
		{
			[DebuggerStepThrough()]
			get { return this._customer_id; }
			set 
			{
				if (this._customer_id != value) 
				{
					this._customer_id = value;
					this.IsDirty = true;	
					OnPropertyChanged("customer_id");
					this._customer_ = null;
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private int _supplier_id = int.MinValue;
		/// <summary>
		/// supplier_id
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, false)]
		public int supplier_id
		{
			[DebuggerStepThrough()]
			get { return this._supplier_id; }
			set 
			{
				if (this._supplier_id != value) 
				{
					this._supplier_id = value;
					this.IsDirty = true;	
					OnPropertyChanged("supplier_id");
					this._supplier_ = null;
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private int _purchaseorder_id = int.MinValue;
		/// <summary>
		/// purchaseorder_id
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, false)]
		public int purchaseorder_id
		{
			[DebuggerStepThrough()]
			get { return this._purchaseorder_id; }
			set 
			{
				if (this._purchaseorder_id != value) 
				{
					this._purchaseorder_id = value;
					this.IsDirty = true;	
					OnPropertyChanged("purchaseorder_id");
					this._purchaseorder_ = null;
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private decimal _freight = decimal.MinValue;
		/// <summary>
		/// freight
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, true)]
		public decimal freight
		{
			[DebuggerStepThrough()]
			get { return this._freight; }
			set 
			{
				if (this._freight != value) 
				{
					this._freight = value;
					this.IsDirty = true;	
					OnPropertyChanged("freight");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private decimal _total = decimal.MinValue;
		/// <summary>
		/// total
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, false)]
		public decimal total
		{
			[DebuggerStepThrough()]
			get { return this._total; }
			set 
			{
				if (this._total != value) 
				{
					this._total = value;
					this.IsDirty = true;	
					OnPropertyChanged("total");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private decimal _tax = decimal.MinValue;
		/// <summary>
		/// tax
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, true)]
		public decimal tax
		{
			[DebuggerStepThrough()]
			get { return this._tax; }
			set 
			{
				if (this._tax != value) 
				{
					this._tax = value;
					this.IsDirty = true;	
					OnPropertyChanged("tax");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private bool _is_downloaded = false;
		/// <summary>
		/// is_downloaded
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, false)]
		public bool is_downloaded
		{
			[DebuggerStepThrough()]
			get { return this._is_downloaded; }
			set 
			{
				if (this._is_downloaded != value) 
				{
					this._is_downloaded = value;
					this.IsDirty = true;	
					OnPropertyChanged("is_downloaded");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private DateTime _creation_datetime = DateTime.MinValue;
		/// <summary>
		/// creation_datetime
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, false)]
		public DateTime creation_datetime
		{
			[DebuggerStepThrough()]
			get { return this._creation_datetime; }
			set 
			{
				if (this._creation_datetime != value) 
				{
					this._creation_datetime = value;
					this.IsDirty = true;	
					OnPropertyChanged("creation_datetime");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private string _local_code = String.Empty;
		/// <summary>
		/// local_code
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, true)]
		public string local_code
		{
			[DebuggerStepThrough()]
			get { return this._local_code; }
			set 
			{
				if (this._local_code != value) 
				{
					this._local_code = value;
					this.IsDirty = true;	
					OnPropertyChanged("local_code");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private DateTime _downloaded_datetime = DateTime.MinValue;
		/// <summary>
		/// downloaded_datetime
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, true)]
		public DateTime downloaded_datetime
		{
			[DebuggerStepThrough()]
			get { return this._downloaded_datetime; }
			set 
			{
				if (this._downloaded_datetime != value) 
				{
					this._downloaded_datetime = value;
					this.IsDirty = true;	
					OnPropertyChanged("downloaded_datetime");
				}
			}
		}
		
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private Company _customer_ = null;
		/// <summary>
		/// The parent Company object
		/// </summary>
		public Company customer_
		{
			get 
			{
				if (_customer_ == null) 
				{
					_customer_ = GetParentEntity(Company.GetCompany(this.customer_id)) as Company;
				}
				return _customer_;
			}
			set
			{
				if(_customer_ != value) 
				{
					_customer_ = value;
					
					if (value != null) 
					{
						this.customer_id = value.company_id;
					}
					else 
					{
						this.customer_id = int.MinValue;
					}
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private PurchaseOrder _purchaseorder_ = null;
		/// <summary>
		/// The parent PurchaseOrder object
		/// </summary>
		public PurchaseOrder purchaseorder_
		{
			get 
			{
				if (_purchaseorder_ == null) 
				{
					_purchaseorder_ = GetParentEntity(PurchaseOrder.GetPurchaseOrder(this.purchaseorder_id)) as PurchaseOrder;
				}
				return _purchaseorder_;
			}
			set
			{
				if(_purchaseorder_ != value) 
				{
					_purchaseorder_ = value;
					
					if (value != null) 
					{
						this.purchaseorder_id = value.purchaseorder_id;
					}
					else 
					{
						this.purchaseorder_id = int.MinValue;
					}
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private Company _supplier_ = null;
		/// <summary>
		/// The parent Company object
		/// </summary>
		public Company supplier_
		{
			get 
			{
				if (_supplier_ == null) 
				{
					_supplier_ = GetParentEntity(Company.GetCompany(this.supplier_id)) as Company;
				}
				return _supplier_;
			}
			set
			{
				if(_supplier_ != value) 
				{
					_supplier_ = value;
					
					if (value != null) 
					{
						this.supplier_id = value.company_id;
					}
					else 
					{
						this.supplier_id = int.MinValue;
					}
				}
			}
		}
		
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private EntityList<InvoiceItem> _invoiceItemsByinvoice_ = null;
		/// <summary>
		/// A collection of InvoiceItem children objects
		/// </summary>
		public EntityList<InvoiceItem> InvoiceItemsByinvoice_
		{
			get 
			{
				if (_invoiceItemsByinvoice_ == null) {
					_invoiceItemsByinvoice_ = HealthStop.Business.InvoiceItem.GetInvoiceItemsByinvoice_(this);
				}
				return _invoiceItemsByinvoice_;
			}
		}	
		#endregion
		
		#region Non-Public Properties
		/// <summary>
		/// Gets the SQL statement for an insert
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		protected override string InsertSPName
		{
			get 
			{
				return typeof(Invoice).Name + "Insert";
			}
		}
		
		/// <summary>
		/// Gets the SQL statement for an update by key
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		protected override string UpdateSPName
		{
			get
			{
				return typeof(Invoice).Name + "Update";
			}
		}
		
		/// <summary>
		/// Gets the SQL statement for a delete by key
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		protected override string DeleteSPName
		{
			get
			{
				return typeof(Invoice).Name + "Delete";
			}
		}
		#endregion
		
		#region Constructors
		/// <summary>
		/// The default protected constructor
		/// </summary>
		protected Invoice() { }
		#endregion
		
		#region Public Methods
		/// <summary>
		/// Creates a InvoiceItem for this Invoice object
		/// </summary>
		public InvoiceItem CreateInvoiceItem()
		{
			return HealthStop.Business.InvoiceItem.CreateInvoiceItemByinvoice_(this);
		}
		

        /// <summary>
        /// Refreshes the entity with data from the data source. Child entity objects and entity list objects will be preserved (ie. they will not be replaced with new objects so that references to them are retained, such as bound data controls).
        /// </summary>
        public override void Refresh()
		{
			this.Replace(GetInvoice(this.invoice_id));
		}

		#endregion
		
		#region Non-Public Methods
		/// <summary>
		/// This is called before an entity is saved to ensure that any parent entities keys are set properly
		/// </summary>
		protected override void EnsureParentProperties()
		{
			if (_customer_ != null)
			{	
				this.customer_id = this.customer_.company_id;
			}
			
			if (_purchaseorder_ != null)
			{	
				this.purchaseorder_id = this.purchaseorder_.purchaseorder_id;
			}
			
			if (_supplier_ != null)
			{	
				this.supplier_id = this.supplier_.company_id;
			}
			
		}
		#endregion
		
		#region Static Properties
		/// <summary>
		/// A list of all fields for this entity in the database. It does not include the 
		/// select keyword, or the table information - just the fields. This can be used
		/// for new dynamic methods.
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		public static string SelectFieldList 
		{
			get 
			{
				return @"
	[Invoices].[invoice_id],
	[Invoices].[customer_id],
	[Invoices].[supplier_id],
	[Invoices].[purchaseorder_id],
	[Invoices].[freight],
	[Invoices].[total],
	[Invoices].[tax],
	[Invoices].[is_downloaded],
	[Invoices].[creation_datetime],
	[Invoices].[local_code],
	[Invoices].[downloaded_datetime]
";
			}
		}
		
		
		/// <summary>
        /// Table Name
        /// </summary>
        public new static string TableName
        {
            get
            {
                return "Invoices";
            }
        }

		#endregion
		
		#region Static Methods
		/// <summary>
		/// Insert a Invoice into the data store based on the primitive properties. This can be used as the 
		/// insert method for an ObjectDataSource.
		/// </summary>
		/// <param name="customer_id">customer_id</param>
		/// <param name="supplier_id">supplier_id</param>
		/// <param name="purchaseorder_id">purchaseorder_id</param>
		/// <param name="freight">freight</param>
		/// <param name="total">total</param>
		/// <param name="tax">tax</param>
		/// <param name="is_downloaded">is_downloaded</param>
		/// <param name="creation_datetime">creation_datetime</param>
		/// <param name="local_code">local_code</param>
		/// <param name="downloaded_datetime">downloaded_datetime</param>
		public static void InsertInvoice(int @customer_id, int @supplier_id, int @purchaseorder_id, decimal @freight, decimal @total, decimal @tax, bool @is_downloaded, DateTime @creation_datetime, string @local_code, DateTime @downloaded_datetime)
		{
            using (SqlHelper helper = new SqlHelper())
            {
                try
                {
                    helper.BeginTransaction();
            		InsertInvoice(@customer_id, @supplier_id, @purchaseorder_id, @freight, @total, @tax, @is_downloaded, @creation_datetime, @local_code, @downloaded_datetime, helper);
                    helper.Commit();
                }
                catch
                {
                    helper.Rollback();
                    throw;
                }
            }
		}

		/// <summary>
		/// Insert a Invoice into the data store based on the primitive properties. This can be used as the 
		/// insert method for an ObjectDataSource.
		/// </summary>
		/// <param name="customer_id">customer_id</param>
		/// <param name="supplier_id">supplier_id</param>
		/// <param name="purchaseorder_id">purchaseorder_id</param>
		/// <param name="freight">freight</param>
		/// <param name="total">total</param>
		/// <param name="tax">tax</param>
		/// <param name="is_downloaded">is_downloaded</param>
		/// <param name="creation_datetime">creation_datetime</param>
		/// <param name="local_code">local_code</param>
		/// <param name="downloaded_datetime">downloaded_datetime</param>
		/// <param name="helper">helper</param>
		internal static void InsertInvoice(int @customer_id, int @supplier_id, int @purchaseorder_id, decimal @freight, decimal @total, decimal @tax, bool @is_downloaded, DateTime @creation_datetime, string @local_code, DateTime @downloaded_datetime, SqlHelper @helper)
		{
			string commandText = "InvoiceInsert";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@customer_id", EntityBase.GetDatabaseValue(@customer_id)));
			parameters.Add(new SqlParameter("@supplier_id", EntityBase.GetDatabaseValue(@supplier_id)));
			parameters.Add(new SqlParameter("@purchaseorder_id", EntityBase.GetDatabaseValue(@purchaseorder_id)));
			parameters.Add(new SqlParameter("@freight", EntityBase.GetDatabaseValue(@freight)));
			parameters.Add(new SqlParameter("@total", EntityBase.GetDatabaseValue(@total)));
			parameters.Add(new SqlParameter("@tax", EntityBase.GetDatabaseValue(@tax)));
			parameters.Add(new SqlParameter("@is_downloaded", @is_downloaded));
			parameters.Add(new SqlParameter("@creation_datetime", EntityBase.GetDatabaseValue(@creation_datetime)));
			parameters.Add(new SqlParameter("@local_code", EntityBase.GetDatabaseValue(@local_code)));
			parameters.Add(new SqlParameter("@downloaded_datetime", EntityBase.GetDatabaseValue(@downloaded_datetime)));
			
			@helper.Execute(commandText, CommandType.StoredProcedure, parameters);
		}
		
		/// <summary>
		/// Updates a Invoice into the data store based on the primitive properties. This can be used as the 
		/// update method for an ObjectDataSource.
		/// </summary>
		/// <param name="invoice_id">invoice_id</param>
		/// <param name="customer_id">customer_id</param>
		/// <param name="supplier_id">supplier_id</param>
		/// <param name="purchaseorder_id">purchaseorder_id</param>
		/// <param name="freight">freight</param>
		/// <param name="total">total</param>
		/// <param name="tax">tax</param>
		/// <param name="is_downloaded">is_downloaded</param>
		/// <param name="creation_datetime">creation_datetime</param>
		/// <param name="local_code">local_code</param>
		/// <param name="downloaded_datetime">downloaded_datetime</param>
		public static void UpdateInvoice(int @invoice_id, int @customer_id, int @supplier_id, int @purchaseorder_id, decimal @freight, decimal @total, decimal @tax, bool @is_downloaded, DateTime @creation_datetime, string @local_code, DateTime @downloaded_datetime)
		{
			using (SqlHelper helper = new SqlHelper()) 
			{
				try
				{
					helper.BeginTransaction();
					UpdateInvoice(@invoice_id, @customer_id, @supplier_id, @purchaseorder_id, @freight, @total, @tax, @is_downloaded, @creation_datetime, @local_code, @downloaded_datetime, helper);
					helper.Commit();
				}
				catch 
				{
					helper.Rollback();	
					throw;
				}
			}
		}
		
		/// <summary>
		/// Updates a Invoice into the data store based on the primitive properties. This can be used as the 
		/// update method for an ObjectDataSource.
		/// </summary>
		/// <param name="invoice_id">invoice_id</param>
		/// <param name="customer_id">customer_id</param>
		/// <param name="supplier_id">supplier_id</param>
		/// <param name="purchaseorder_id">purchaseorder_id</param>
		/// <param name="freight">freight</param>
		/// <param name="total">total</param>
		/// <param name="tax">tax</param>
		/// <param name="is_downloaded">is_downloaded</param>
		/// <param name="creation_datetime">creation_datetime</param>
		/// <param name="local_code">local_code</param>
		/// <param name="downloaded_datetime">downloaded_datetime</param>
		/// <param name="helper">helper</param>
		internal static void UpdateInvoice(int @invoice_id, int @customer_id, int @supplier_id, int @purchaseorder_id, decimal @freight, decimal @total, decimal @tax, bool @is_downloaded, DateTime @creation_datetime, string @local_code, DateTime @downloaded_datetime, SqlHelper @helper)
		{
			string commandText = "InvoiceUpdate";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@invoice_id", EntityBase.GetDatabaseValue(@invoice_id)));
			parameters.Add(new SqlParameter("@customer_id", EntityBase.GetDatabaseValue(@customer_id)));
			parameters.Add(new SqlParameter("@supplier_id", EntityBase.GetDatabaseValue(@supplier_id)));
			parameters.Add(new SqlParameter("@purchaseorder_id", EntityBase.GetDatabaseValue(@purchaseorder_id)));
			parameters.Add(new SqlParameter("@freight", EntityBase.GetDatabaseValue(@freight)));
			parameters.Add(new SqlParameter("@total", EntityBase.GetDatabaseValue(@total)));
			parameters.Add(new SqlParameter("@tax", EntityBase.GetDatabaseValue(@tax)));
			parameters.Add(new SqlParameter("@is_downloaded", @is_downloaded));
			parameters.Add(new SqlParameter("@creation_datetime", EntityBase.GetDatabaseValue(@creation_datetime)));
			parameters.Add(new SqlParameter("@local_code", EntityBase.GetDatabaseValue(@local_code)));
			parameters.Add(new SqlParameter("@downloaded_datetime", EntityBase.GetDatabaseValue(@downloaded_datetime)));
			
			@helper.Execute(commandText, CommandType.StoredProcedure, parameters);
		}
		
		/// <summary>
		/// Deletes a Invoice from the data store based on the primitive primary keys. This can be used as the 
		/// delete method for an ObjectDataSource.
		/// </summary>
		/// <param name="invoice_id">invoice_id</param>
		public static void DeleteInvoice(int @invoice_id)
		{
			using (SqlHelper helper = new SqlHelper()) 
			{
				try 
				{
					helper.BeginTransaction();
					DeleteInvoice(@invoice_id, helper);
					helper.Commit();
				} 
				catch 
				{
					helper.Rollback();
					throw;
				}
			}
		}
		
		/// <summary>
		/// Deletes a Invoice from the data store based on the primitive primary keys. This can be used as the 
		/// delete method for an ObjectDataSource.
		/// </summary>
		/// <param name="invoice_id">invoice_id</param>
		/// <param name="helper">helper</param>
		internal static void DeleteInvoice(int @invoice_id, SqlHelper @helper)
		{
			string commandText = "InvoiceDelete";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@invoice_id", @invoice_id));
		
			@helper.Execute(commandText, CommandType.StoredProcedure, parameters);
		}
		
		/// <summary>
		/// Creates a new Invoice object.
		/// </summary>
		/// <returns>The newly created Invoice object.</returns>
		public static Invoice CreateInvoice()
		{
			return InitializeNew<Invoice>();
		}
		
		/// <summary>
		/// Retrieve information for a Invoice by a Invoice's unique identifier.
		/// </summary>
		/// <param name="invoice_id">invoice_id</param>
		/// <returns>Invoice</returns>
		public static Invoice GetInvoice(int invoice_id)
		{
			string commandText = "InvoiceGet";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@invoice_id", invoice_id));
			
			return GetOne<Invoice>(commandText, parameters);
		}
		
		/// <summary>
		/// Gets a collection Invoice objects.
		/// </summary>
		/// <returns>The retrieved collection of Invoice objects.</returns>
		public static EntityList<Invoice> GetInvoices()
		{
			string commandText = "InvoiceGetAll";
		
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			return GetList<Invoice>(commandText, parameters);
		}
		
		/// <summary>
        /// Gets a collection Invoice objects.
        /// </summary>
		/// <param name="orderBy">order by</param>
		/// <param name="startRowIndex">Start Row Index</param>
		/// <param name="pageSize">PageSize</param>
		/// <param name="totalRows">Total rows</param>
        /// <returns>The retrieved collection of Invoice objects.</returns>
        protected static EntityList<Invoice> GetInvoices(string orderBy, int startRowIndex, int pageSize, out long totalRows)
        {
            return GetList<Invoice>(SelectFieldList, "FROM [dbo].[Invoices]", new List<SqlParameter>(),orderBy,  startRowIndex, pageSize, out totalRows);
        }

		/// <summary>
        /// Gets a collection Invoice objects.
        /// </summary>
		/// <param name="startRowIndex">Start Row Index</param>
		/// <param name="pageSize">Page Size</param>
		/// <param name="totalRows">Total rows</param>
        /// <returns>The retrieved collection of Invoice objects.</returns>
        public static EntityList<Invoice> GetInvoices(int startRowIndex, int pageSize, out long totalRows)
        {
            return GetList<Invoice>(SelectFieldList, "FROM [dbo].[Invoices]", new List<SqlParameter>(), null,  startRowIndex, pageSize, out totalRows);
        }
		
		/// <summary>
		/// Gets a collection Invoice objects by custom where clause.
		/// </summary>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameter">The parameter that is in the where clause</param>
		/// <param name="orderBy">the order by clause. Should start with "order by"</param>
		/// <returns>The retrieved collection of Invoice objects.</returns>
		protected static EntityList<Invoice> GetInvoices(string where, SqlParameter parameter, string orderBy)
		{
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			parameters.Add(parameter);
						
			return GetInvoices(string.Empty, where, parameters, orderBy);
		}
		
		/// <summary>
		/// Gets a collection Invoice objects by custom where clause.
		/// </summary>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameter">The parameter that is in the where clause</param>
		/// <returns>The retrieved collection of Invoice objects.</returns>
		protected static EntityList<Invoice> GetInvoices(string where, SqlParameter parameter)
		{
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			parameters.Add(parameter);
						
			return GetInvoices(string.Empty, where, parameters, Invoice.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection Invoice objects by custom where clause.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameter">The parameter that is in the where clause</param>
		/// <returns>The retrieved collection of Invoice objects.</returns>
		protected static EntityList<Invoice> GetInvoices(string prefix, string where, SqlParameter parameter)
		{
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			parameters.Add(parameter);
						
			return GetInvoices(prefix, where, parameters, Invoice.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection Invoice objects by custom where clause.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameters">The parameters that are listed in the where clause</param>
		/// <returns>The retrieved collection of Invoice objects.</returns>
		protected static EntityList<Invoice> GetInvoices(string where, System.Collections.Generic.List<SqlParameter> parameters)
		{
			return GetInvoices(string.Empty, where, parameters, Invoice.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection Invoice objects by custom where clause.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameters">The parameters that are listed in the where clause</param>
		/// <returns>The retrieved collection of Invoice objects.</returns>
		protected static EntityList<Invoice> GetInvoices(string prefix, string where, System.Collections.Generic.List<SqlParameter> parameters)
		{
			return GetInvoices(prefix, where, parameters, Invoice.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection Invoice objects by custom where clause and order by.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameters">The parameters that are listed in the where clause</param>
		/// <param name="orderBy">the order by clause. Shoudl start with "order by"</param>
		/// <returns>The retrieved collection of Invoice objects.</returns>
		protected static EntityList<Invoice> GetInvoices(string prefix, string where, System.Collections.Generic.List<SqlParameter> parameters, string orderBy)
		{
			string commandText = @"SELECT " + prefix + "" + Invoice.SelectFieldList + "FROM [dbo].[Invoices] " + where + " " + orderBy;			
			
			using (SqlHelper helper = new SqlHelper()) 
			{
				using (IDataReader reader = helper.ExecuteDataReader(commandText, CommandType.Text, parameters))
				{
					return EntityBase.InitializeList<Invoice>(reader);
				}
			}
		}		
		
		/// <summary>
        /// Gets a collection Address objects.
        /// </summary>
		/// <param name="orderBy">order by</param>
		/// <param name="where">where</param>
		/// <param name=parameters">parameters</param>
		/// <param name="startRowIndex">Start Row Index</param>
		/// <param name="pageSize">PageSize</param>
		/// <param name="totalRows">Total rows</param>
        /// <returns>The retrieved collection of Address objects.</returns>
        protected static EntityList<Invoice> GetInvoices(string orderBy, string where, System.Collections.Generic.List<SqlParameter> parameters, int startRowIndex, int pageSize, out long totalRows)
        {
            return GetList<Invoice>(SelectFieldList, "FROM [dbo].[Invoices] " + where, parameters, orderBy, startRowIndex, pageSize, out totalRows);			
		}
		
		/// <summary>
		/// Gets a collection of Invoice objects by a Company object.
		/// </summary>
		/// <param name="customer_">customer_</param>
		/// <returns>A collection Invoice objects.</returns>
		public static EntityList<Invoice> GetInvoicesBycustomer_(Company @customer_) 
		{
			string commandText = "InvoiceGetByCompany";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@customer_id", @customer_.company_id));
			
			return GetList<Invoice>(@customer_, commandText, parameters);
		}
  

		/// <summary>
		/// Gets a collection of Invoice objects by a Company object.
		/// </summary>
		/// <param name="company">company</param>
        /// <param name="orderBy"></param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection Invoice objects.</returns>
		protected static EntityList<Invoice> GetInvoicesBycustomer_(Company @customer_, string orderBy, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[Invoices] 
WHERE 
	[Invoices].[customer_id] = @customer_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
				
			parameters.Add(new SqlParameter("@customer_id", @customer_.company_id));
			
			return GetList<Invoice>(SelectFieldList, commandText, parameters, orderBy, startRowIndex, pageSize, out totalRows);
		}

	    /// <summary>
		/// Gets a collection of Invoice objects by a Company object.
		/// </summary>
		/// <param name="company_id">company_id</param>
        /// <param name="orderBy"></param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection Invoice objects.</returns>
		protected static EntityList<Invoice> GetInvoicesBycustomer_(int @company_id, string orderBy, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[Invoices] 
WHERE 
	[Invoices].[customer_id] = @customer_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@customer_id", @company_id));
			
			return GetList<Invoice>(SelectFieldList, commandText, parameters, orderBy, startRowIndex, pageSize, out totalRows);
		}		
		
		
		/// <summary>
		/// Gets a collection of Invoice objects by a Company object.
		/// </summary>
		/// <param name="company">company</param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection Invoice objects.</returns>
		public static EntityList<Invoice> GetInvoicesBycustomer_(Company @customer_, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[Invoices] 
WHERE 
	[Invoices].[customer_id] = @customer_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
				
			parameters.Add(new SqlParameter("@customer_id", @customer_.company_id));
			
			return GetList<Invoice>(SelectFieldList, commandText, parameters, null, startRowIndex, pageSize, out totalRows);
		}

	    /// <summary>
		/// Gets a collection of Invoice objects by a Company object.
		/// </summary>
		/// <param name="company_id">company_id</param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection Invoice objects.</returns>
		public static EntityList<Invoice> GetInvoicesBycustomer_(int @company_id, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[Invoices] 
WHERE 
	[Invoices].[customer_id] = @customer_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@customer_id", @company_id));
			
			return GetList<Invoice>(SelectFieldList, commandText, parameters, null, startRowIndex, pageSize, out totalRows);
		}
		
	
		/// <summary>
		/// Gets a collection of Invoice objects by a Company unique identifier.
		/// </summary>
		/// <param name="company_id">company_id</param>
		/// <returns>A collection Invoice objects.</returns>
		public static EntityList<Invoice> GetInvoicesBycustomer_(int @company_id) 
		{
			string commandText = "InvoiceGetByCompany";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@customer_id", @company_id));
			
			return GetList<Invoice>(commandText, parameters);
		}

		/// <summary>
		/// Create a new Invoice object from a Company object.
		/// </summary>
		/// <param name="customer_">customer_</param>
		/// <returns>The newly created Invoice object.</returns>
		public static Invoice CreateInvoiceBycustomer_(Company @customer_)
		{
			Invoice invoice = InitializeNew<Invoice>();
			
			invoice.customer_id = @customer_.company_id;
			
			invoice.customer_ = @customer_;
			
			return invoice;
		}
		
		/// <summary>
		/// Deletes Invoice objects by a Company object.
		/// </summary>
		/// <param name="company">company</param>
		public static void DeleteInvoicesBycustomer_(Company company) 
		{
			string commandText = "InvoiceDeleteByCompany";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@customer_id", company.company_id));
			
			using (SqlHelper helper = new SqlHelper()) 
			{
				helper.Execute(commandText, CommandType.StoredProcedure, parameters);
			}
		}
		
		/// <summary>
		/// Deletes Invoice objects by a Company unique identifier.
		/// </summary>
		/// <param name="company_id">company_id</param>
		public static void DeleteInvoicesBycustomer_(int company_id) 
		{
			string commandText = "InvoiceDeleteByCompany";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@customer_id", company_id));
			
			using (SqlHelper helper = new SqlHelper()) 
			{
				helper.Execute(commandText, CommandType.StoredProcedure, parameters);
			}
		}
		/// <summary>
		/// Gets a collection of Invoice objects by a PurchaseOrder object.
		/// </summary>
		/// <param name="purchaseorder_">purchaseorder_</param>
		/// <returns>A collection Invoice objects.</returns>
		public static EntityList<Invoice> GetInvoicesBypurchaseorder_(PurchaseOrder @purchaseorder_) 
		{
			string commandText = "InvoiceGetByPurchaseOrder";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@purchaseorder_id", @purchaseorder_.purchaseorder_id));
			
			return GetList<Invoice>(@purchaseorder_, commandText, parameters);
		}
  

		/// <summary>
		/// Gets a collection of Invoice objects by a PurchaseOrder object.
		/// </summary>
		/// <param name="purchaseOrder">purchaseOrder</param>
        /// <param name="orderBy"></param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection Invoice objects.</returns>
		protected static EntityList<Invoice> GetInvoicesBypurchaseorder_(PurchaseOrder @purchaseorder_, string orderBy, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[Invoices] 
WHERE 
	[Invoices].[purchaseorder_id] = @purchaseorder_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
				
			parameters.Add(new SqlParameter("@purchaseorder_id", @purchaseorder_.purchaseorder_id));
			
			return GetList<Invoice>(SelectFieldList, commandText, parameters, orderBy, startRowIndex, pageSize, out totalRows);
		}

	    /// <summary>
		/// Gets a collection of Invoice objects by a PurchaseOrder object.
		/// </summary>
		/// <param name="purchaseorder_id">purchaseorder_id</param>
        /// <param name="orderBy"></param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection Invoice objects.</returns>
		protected static EntityList<Invoice> GetInvoicesBypurchaseorder_(int @purchaseorder_id, string orderBy, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[Invoices] 
WHERE 
	[Invoices].[purchaseorder_id] = @purchaseorder_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@purchaseorder_id", @purchaseorder_id));
			
			return GetList<Invoice>(SelectFieldList, commandText, parameters, orderBy, startRowIndex, pageSize, out totalRows);
		}		
		
		
		/// <summary>
		/// Gets a collection of Invoice objects by a PurchaseOrder object.
		/// </summary>
		/// <param name="purchaseOrder">purchaseOrder</param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection Invoice objects.</returns>
		public static EntityList<Invoice> GetInvoicesBypurchaseorder_(PurchaseOrder @purchaseorder_, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[Invoices] 
WHERE 
	[Invoices].[purchaseorder_id] = @purchaseorder_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
				
			parameters.Add(new SqlParameter("@purchaseorder_id", @purchaseorder_.purchaseorder_id));
			
			return GetList<Invoice>(SelectFieldList, commandText, parameters, null, startRowIndex, pageSize, out totalRows);
		}

	    /// <summary>
		/// Gets a collection of Invoice objects by a PurchaseOrder object.
		/// </summary>
		/// <param name="purchaseorder_id">purchaseorder_id</param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection Invoice objects.</returns>
		public static EntityList<Invoice> GetInvoicesBypurchaseorder_(int @purchaseorder_id, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[Invoices] 
WHERE 
	[Invoices].[purchaseorder_id] = @purchaseorder_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@purchaseorder_id", @purchaseorder_id));
			
			return GetList<Invoice>(SelectFieldList, commandText, parameters, null, startRowIndex, pageSize, out totalRows);
		}
		
	
		/// <summary>
		/// Gets a collection of Invoice objects by a PurchaseOrder unique identifier.
		/// </summary>
		/// <param name="purchaseorder_id">purchaseorder_id</param>
		/// <returns>A collection Invoice objects.</returns>
		public static EntityList<Invoice> GetInvoicesBypurchaseorder_(int @purchaseorder_id) 
		{
			string commandText = "InvoiceGetByPurchaseOrder";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@purchaseorder_id", @purchaseorder_id));
			
			return GetList<Invoice>(commandText, parameters);
		}

		/// <summary>
		/// Create a new Invoice object from a PurchaseOrder object.
		/// </summary>
		/// <param name="purchaseorder_">purchaseorder_</param>
		/// <returns>The newly created Invoice object.</returns>
		public static Invoice CreateInvoiceBypurchaseorder_(PurchaseOrder @purchaseorder_)
		{
			Invoice invoice = InitializeNew<Invoice>();
			
			invoice.purchaseorder_id = @purchaseorder_.purchaseorder_id;
			
			invoice.purchaseorder_ = @purchaseorder_;
			
			return invoice;
		}
		
		/// <summary>
		/// Deletes Invoice objects by a PurchaseOrder object.
		/// </summary>
		/// <param name="purchaseOrder">purchaseOrder</param>
		public static void DeleteInvoicesBypurchaseorder_(PurchaseOrder purchaseOrder) 
		{
			string commandText = "InvoiceDeleteByPurchaseOrder";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@purchaseorder_id", purchaseOrder.purchaseorder_id));
			
			using (SqlHelper helper = new SqlHelper()) 
			{
				helper.Execute(commandText, CommandType.StoredProcedure, parameters);
			}
		}
		
		/// <summary>
		/// Deletes Invoice objects by a PurchaseOrder unique identifier.
		/// </summary>
		/// <param name="purchaseorder_id">purchaseorder_id</param>
		public static void DeleteInvoicesBypurchaseorder_(int purchaseorder_id) 
		{
			string commandText = "InvoiceDeleteByPurchaseOrder";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@purchaseorder_id", purchaseorder_id));
			
			using (SqlHelper helper = new SqlHelper()) 
			{
				helper.Execute(commandText, CommandType.StoredProcedure, parameters);
			}
		}
		/// <summary>
		/// Gets a collection of Invoice objects by a Company object.
		/// </summary>
		/// <param name="supplier_">supplier_</param>
		/// <returns>A collection Invoice objects.</returns>
		public static EntityList<Invoice> GetInvoicesBysupplier_(Company @supplier_) 
		{
			string commandText = "InvoiceGetByCompany";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@supplier_id", @supplier_.company_id));
			
			return GetList<Invoice>(@supplier_, commandText, parameters);
		}
  

		/// <summary>
		/// Gets a collection of Invoice objects by a Company object.
		/// </summary>
		/// <param name="company">company</param>
        /// <param name="orderBy"></param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection Invoice objects.</returns>
		protected static EntityList<Invoice> GetInvoicesBysupplier_(Company @supplier_, string orderBy, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[Invoices] 
WHERE 
	[Invoices].[supplier_id] = @supplier_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
				
			parameters.Add(new SqlParameter("@supplier_id", @supplier_.company_id));
			
			return GetList<Invoice>(SelectFieldList, commandText, parameters, orderBy, startRowIndex, pageSize, out totalRows);
		}

	    /// <summary>
		/// Gets a collection of Invoice objects by a Company object.
		/// </summary>
		/// <param name="company_id">company_id</param>
        /// <param name="orderBy"></param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection Invoice objects.</returns>
		protected static EntityList<Invoice> GetInvoicesBysupplier_(int @company_id, string orderBy, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[Invoices] 
WHERE 
	[Invoices].[supplier_id] = @supplier_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@supplier_id", @company_id));
			
			return GetList<Invoice>(SelectFieldList, commandText, parameters, orderBy, startRowIndex, pageSize, out totalRows);
		}		
		
		
		/// <summary>
		/// Gets a collection of Invoice objects by a Company object.
		/// </summary>
		/// <param name="company">company</param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection Invoice objects.</returns>
		public static EntityList<Invoice> GetInvoicesBysupplier_(Company @supplier_, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[Invoices] 
WHERE 
	[Invoices].[supplier_id] = @supplier_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
				
			parameters.Add(new SqlParameter("@supplier_id", @supplier_.company_id));
			
			return GetList<Invoice>(SelectFieldList, commandText, parameters, null, startRowIndex, pageSize, out totalRows);
		}

	    /// <summary>
		/// Gets a collection of Invoice objects by a Company object.
		/// </summary>
		/// <param name="company_id">company_id</param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection Invoice objects.</returns>
		public static EntityList<Invoice> GetInvoicesBysupplier_(int @company_id, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[Invoices] 
WHERE 
	[Invoices].[supplier_id] = @supplier_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@supplier_id", @company_id));
			
			return GetList<Invoice>(SelectFieldList, commandText, parameters, null, startRowIndex, pageSize, out totalRows);
		}
		
	
		/// <summary>
		/// Gets a collection of Invoice objects by a Company unique identifier.
		/// </summary>
		/// <param name="company_id">company_id</param>
		/// <returns>A collection Invoice objects.</returns>
		public static EntityList<Invoice> GetInvoicesBysupplier_(int @company_id) 
		{
			string commandText = "InvoiceGetByCompany";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@supplier_id", @company_id));
			
			return GetList<Invoice>(commandText, parameters);
		}

		/// <summary>
		/// Create a new Invoice object from a Company object.
		/// </summary>
		/// <param name="supplier_">supplier_</param>
		/// <returns>The newly created Invoice object.</returns>
		public static Invoice CreateInvoiceBysupplier_(Company @supplier_)
		{
			Invoice invoice = InitializeNew<Invoice>();
			
			invoice.supplier_id = @supplier_.company_id;
			
			invoice.supplier_ = @supplier_;
			
			return invoice;
		}
		
		/// <summary>
		/// Deletes Invoice objects by a Company object.
		/// </summary>
		/// <param name="company">company</param>
		public static void DeleteInvoicesBysupplier_(Company company) 
		{
			string commandText = "InvoiceDeleteByCompany";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@supplier_id", company.company_id));
			
			using (SqlHelper helper = new SqlHelper()) 
			{
				helper.Execute(commandText, CommandType.StoredProcedure, parameters);
			}
		}
		
		/// <summary>
		/// Deletes Invoice objects by a Company unique identifier.
		/// </summary>
		/// <param name="company_id">company_id</param>
		public static void DeleteInvoicesBysupplier_(int company_id) 
		{
			string commandText = "InvoiceDeleteByCompany";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@supplier_id", company_id));
			
			using (SqlHelper helper = new SqlHelper()) 
			{
				helper.Execute(commandText, CommandType.StoredProcedure, parameters);
			}
		}
		#endregion
		
		#region Subclasses
		public static partial class InvoiceProperties
		{
			public const string invoice_id = "invoice_id";
			public const string customer_id = "customer_id";
			public const string supplier_id = "supplier_id";
			public const string purchaseorder_id = "purchaseorder_id";
			public const string freight = "freight";
			public const string total = "total";
			public const string tax = "tax";
			public const string is_downloaded = "is_downloaded";
			public const string creation_datetime = "creation_datetime";
			public const string local_code = "local_code";
			public const string downloaded_datetime = "downloaded_datetime";
		}
		#endregion
	}
}
