/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 10/08/2012 7:48:55 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;

using HealthStop.Business.Framework;


namespace HealthStop.Business
{
	/// <summary>
	/// This object represents the properties and methods of a AllowedStore.
	/// </summary>
	[Serializable()]
	[DebuggerDisplay("entry_id: {entry_id}")]
	public partial class AllowedStore
	{
		#region Public Properties
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private int _entry_id = int.MinValue;
		/// <summary>
		/// entry_id
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(true, true, false)]
		public int entry_id
		{
			[DebuggerStepThrough()]
			get { return this._entry_id; }
			protected set 
			{
				if (this._entry_id != value) 
				{
					this._entry_id = value;
					this.IsDirty = true;	
					OnPropertyChanged("entry_id");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private int _customer_id = int.MinValue;
		/// <summary>
		/// customer_id
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, false)]
		public int customer_id
		{
			[DebuggerStepThrough()]
			get { return this._customer_id; }
			set 
			{
				if (this._customer_id != value) 
				{
					this._customer_id = value;
					this.IsDirty = true;	
					OnPropertyChanged("customer_id");
					this._customer_ = null;
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private int _supplier_id = int.MinValue;
		/// <summary>
		/// supplier_id
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, false)]
		public int supplier_id
		{
			[DebuggerStepThrough()]
			get { return this._supplier_id; }
			set 
			{
				if (this._supplier_id != value) 
				{
					this._supplier_id = value;
					this.IsDirty = true;	
					OnPropertyChanged("supplier_id");
					this._supplier_ = null;
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private string _account_number = String.Empty;
		/// <summary>
		/// account_number
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, false)]
		public string account_number
		{
			[DebuggerStepThrough()]
			get { return this._account_number; }
			set 
			{
				if (this._account_number != value) 
				{
					this._account_number = value;
					this.IsDirty = true;	
					OnPropertyChanged("account_number");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private bool _is_member = false;
		/// <summary>
		/// is_member
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, false)]
		public bool is_member
		{
			[DebuggerStepThrough()]
			get { return this._is_member; }
			set 
			{
				if (this._is_member != value) 
				{
					this._is_member = value;
					this.IsDirty = true;	
					OnPropertyChanged("is_member");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private string _authoriser_email = String.Empty;
		/// <summary>
		/// authoriser_email
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, false)]
		public string authoriser_email
		{
			[DebuggerStepThrough()]
			get { return this._authoriser_email; }
			set 
			{
				if (this._authoriser_email != value) 
				{
					this._authoriser_email = value;
					this.IsDirty = true;	
					OnPropertyChanged("authoriser_email");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private DateTime _creation_datetime = DateTime.MinValue;
		/// <summary>
		/// creation_datetime
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, false)]
		public DateTime creation_datetime
		{
			[DebuggerStepThrough()]
			get { return this._creation_datetime; }
			set 
			{
				if (this._creation_datetime != value) 
				{
					this._creation_datetime = value;
					this.IsDirty = true;	
					OnPropertyChanged("creation_datetime");
				}
			}
		}
		
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private Company _customer_ = null;
		/// <summary>
		/// The parent Company object
		/// </summary>
		public Company customer_
		{
			get 
			{
				if (_customer_ == null) 
				{
					_customer_ = GetParentEntity(Company.GetCompany(this.customer_id)) as Company;
				}
				return _customer_;
			}
			set
			{
				if(_customer_ != value) 
				{
					_customer_ = value;
					
					if (value != null) 
					{
						this.customer_id = value.company_id;
					}
					else 
					{
						this.customer_id = int.MinValue;
					}
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private Company _supplier_ = null;
		/// <summary>
		/// The parent Company object
		/// </summary>
		public Company supplier_
		{
			get 
			{
				if (_supplier_ == null) 
				{
					_supplier_ = GetParentEntity(Company.GetCompany(this.supplier_id)) as Company;
				}
				return _supplier_;
			}
			set
			{
				if(_supplier_ != value) 
				{
					_supplier_ = value;
					
					if (value != null) 
					{
						this.supplier_id = value.company_id;
					}
					else 
					{
						this.supplier_id = int.MinValue;
					}
				}
			}
		}
		
		
		#endregion
		
		#region Non-Public Properties
		/// <summary>
		/// Gets the SQL statement for an insert
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		protected override string InsertSPName
		{
			get 
			{
				return typeof(AllowedStore).Name + "Insert";
			}
		}
		
		/// <summary>
		/// Gets the SQL statement for an update by key
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		protected override string UpdateSPName
		{
			get
			{
				return typeof(AllowedStore).Name + "Update";
			}
		}
		
		/// <summary>
		/// Gets the SQL statement for a delete by key
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		protected override string DeleteSPName
		{
			get
			{
				return typeof(AllowedStore).Name + "Delete";
			}
		}
		#endregion
		
		#region Constructors
		/// <summary>
		/// The default protected constructor
		/// </summary>
		protected AllowedStore() { }
		#endregion
		
		#region Public Methods
		

        /// <summary>
        /// Refreshes the entity with data from the data source. Child entity objects and entity list objects will be preserved (ie. they will not be replaced with new objects so that references to them are retained, such as bound data controls).
        /// </summary>
        public override void Refresh()
		{
			this.Replace(GetAllowedStore(this.entry_id));
		}

		#endregion
		
		#region Non-Public Methods
		/// <summary>
		/// This is called before an entity is saved to ensure that any parent entities keys are set properly
		/// </summary>
		protected override void EnsureParentProperties()
		{
			if (_customer_ != null)
			{	
				this.customer_id = this.customer_.company_id;
			}
			
			if (_supplier_ != null)
			{	
				this.supplier_id = this.supplier_.company_id;
			}
			
		}
		#endregion
		
		#region Static Properties
		/// <summary>
		/// A list of all fields for this entity in the database. It does not include the 
		/// select keyword, or the table information - just the fields. This can be used
		/// for new dynamic methods.
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		public static string SelectFieldList 
		{
			get 
			{
				return @"
	[AllowedStores].[entry_id],
	[AllowedStores].[customer_id],
	[AllowedStores].[supplier_id],
	[AllowedStores].[account_number],
	[AllowedStores].[is_member],
	[AllowedStores].[authoriser_email],
	[AllowedStores].[creation_datetime]
";
			}
		}
		
		
		/// <summary>
        /// Table Name
        /// </summary>
        public new static string TableName
        {
            get
            {
                return "AllowedStores";
            }
        }

		#endregion
		
		#region Static Methods
		/// <summary>
		/// Insert a AllowedStore into the data store based on the primitive properties. This can be used as the 
		/// insert method for an ObjectDataSource.
		/// </summary>
		/// <param name="customer_id">customer_id</param>
		/// <param name="supplier_id">supplier_id</param>
		/// <param name="account_number">account_number</param>
		/// <param name="is_member">is_member</param>
		/// <param name="authoriser_email">authoriser_email</param>
		/// <param name="creation_datetime">creation_datetime</param>
		public static void InsertAllowedStore(int @customer_id, int @supplier_id, string @account_number, bool @is_member, string @authoriser_email, DateTime @creation_datetime)
		{
            using (SqlHelper helper = new SqlHelper())
            {
                try
                {
                    helper.BeginTransaction();
            		InsertAllowedStore(@customer_id, @supplier_id, @account_number, @is_member, @authoriser_email, @creation_datetime, helper);
                    helper.Commit();
                }
                catch
                {
                    helper.Rollback();
                    throw;
                }
            }
		}

		/// <summary>
		/// Insert a AllowedStore into the data store based on the primitive properties. This can be used as the 
		/// insert method for an ObjectDataSource.
		/// </summary>
		/// <param name="customer_id">customer_id</param>
		/// <param name="supplier_id">supplier_id</param>
		/// <param name="account_number">account_number</param>
		/// <param name="is_member">is_member</param>
		/// <param name="authoriser_email">authoriser_email</param>
		/// <param name="creation_datetime">creation_datetime</param>
		/// <param name="helper">helper</param>
		internal static void InsertAllowedStore(int @customer_id, int @supplier_id, string @account_number, bool @is_member, string @authoriser_email, DateTime @creation_datetime, SqlHelper @helper)
		{
			string commandText = "AllowedStoreInsert";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@customer_id", EntityBase.GetDatabaseValue(@customer_id)));
			parameters.Add(new SqlParameter("@supplier_id", EntityBase.GetDatabaseValue(@supplier_id)));
			parameters.Add(new SqlParameter("@account_number", EntityBase.GetDatabaseValue(@account_number)));
			parameters.Add(new SqlParameter("@is_member", @is_member));
			parameters.Add(new SqlParameter("@authoriser_email", EntityBase.GetDatabaseValue(@authoriser_email)));
			parameters.Add(new SqlParameter("@creation_datetime", EntityBase.GetDatabaseValue(@creation_datetime)));
			
			@helper.Execute(commandText, CommandType.StoredProcedure, parameters);
		}
		
		/// <summary>
		/// Updates a AllowedStore into the data store based on the primitive properties. This can be used as the 
		/// update method for an ObjectDataSource.
		/// </summary>
		/// <param name="entry_id">entry_id</param>
		/// <param name="customer_id">customer_id</param>
		/// <param name="supplier_id">supplier_id</param>
		/// <param name="account_number">account_number</param>
		/// <param name="is_member">is_member</param>
		/// <param name="authoriser_email">authoriser_email</param>
		/// <param name="creation_datetime">creation_datetime</param>
		public static void UpdateAllowedStore(int @entry_id, int @customer_id, int @supplier_id, string @account_number, bool @is_member, string @authoriser_email, DateTime @creation_datetime)
		{
			using (SqlHelper helper = new SqlHelper()) 
			{
				try
				{
					helper.BeginTransaction();
					UpdateAllowedStore(@entry_id, @customer_id, @supplier_id, @account_number, @is_member, @authoriser_email, @creation_datetime, helper);
					helper.Commit();
				}
				catch 
				{
					helper.Rollback();	
					throw;
				}
			}
		}
		
		/// <summary>
		/// Updates a AllowedStore into the data store based on the primitive properties. This can be used as the 
		/// update method for an ObjectDataSource.
		/// </summary>
		/// <param name="entry_id">entry_id</param>
		/// <param name="customer_id">customer_id</param>
		/// <param name="supplier_id">supplier_id</param>
		/// <param name="account_number">account_number</param>
		/// <param name="is_member">is_member</param>
		/// <param name="authoriser_email">authoriser_email</param>
		/// <param name="creation_datetime">creation_datetime</param>
		/// <param name="helper">helper</param>
		internal static void UpdateAllowedStore(int @entry_id, int @customer_id, int @supplier_id, string @account_number, bool @is_member, string @authoriser_email, DateTime @creation_datetime, SqlHelper @helper)
		{
			string commandText = "AllowedStoreUpdate";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@entry_id", EntityBase.GetDatabaseValue(@entry_id)));
			parameters.Add(new SqlParameter("@customer_id", EntityBase.GetDatabaseValue(@customer_id)));
			parameters.Add(new SqlParameter("@supplier_id", EntityBase.GetDatabaseValue(@supplier_id)));
			parameters.Add(new SqlParameter("@account_number", EntityBase.GetDatabaseValue(@account_number)));
			parameters.Add(new SqlParameter("@is_member", @is_member));
			parameters.Add(new SqlParameter("@authoriser_email", EntityBase.GetDatabaseValue(@authoriser_email)));
			parameters.Add(new SqlParameter("@creation_datetime", EntityBase.GetDatabaseValue(@creation_datetime)));
			
			@helper.Execute(commandText, CommandType.StoredProcedure, parameters);
		}
		
		/// <summary>
		/// Deletes a AllowedStore from the data store based on the primitive primary keys. This can be used as the 
		/// delete method for an ObjectDataSource.
		/// </summary>
		/// <param name="entry_id">entry_id</param>
		public static void DeleteAllowedStore(int @entry_id)
		{
			using (SqlHelper helper = new SqlHelper()) 
			{
				try 
				{
					helper.BeginTransaction();
					DeleteAllowedStore(@entry_id, helper);
					helper.Commit();
				} 
				catch 
				{
					helper.Rollback();
					throw;
				}
			}
		}
		
		/// <summary>
		/// Deletes a AllowedStore from the data store based on the primitive primary keys. This can be used as the 
		/// delete method for an ObjectDataSource.
		/// </summary>
		/// <param name="entry_id">entry_id</param>
		/// <param name="helper">helper</param>
		internal static void DeleteAllowedStore(int @entry_id, SqlHelper @helper)
		{
			string commandText = "AllowedStoreDelete";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@entry_id", @entry_id));
		
			@helper.Execute(commandText, CommandType.StoredProcedure, parameters);
		}
		
		/// <summary>
		/// Creates a new AllowedStore object.
		/// </summary>
		/// <returns>The newly created AllowedStore object.</returns>
		public static AllowedStore CreateAllowedStore()
		{
			return InitializeNew<AllowedStore>();
		}
		
		/// <summary>
		/// Retrieve information for a AllowedStore by a AllowedStore's unique identifier.
		/// </summary>
		/// <param name="entry_id">entry_id</param>
		/// <returns>AllowedStore</returns>
		public static AllowedStore GetAllowedStore(int entry_id)
		{
			string commandText = "AllowedStoreGet";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@entry_id", entry_id));
			
			return GetOne<AllowedStore>(commandText, parameters);
		}
		
		/// <summary>
		/// Gets a collection AllowedStore objects.
		/// </summary>
		/// <returns>The retrieved collection of AllowedStore objects.</returns>
		public static EntityList<AllowedStore> GetAllowedStores()
		{
			string commandText = "AllowedStoreGetAll";
		
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			return GetList<AllowedStore>(commandText, parameters);
		}
		
		/// <summary>
        /// Gets a collection AllowedStore objects.
        /// </summary>
		/// <param name="orderBy">order by</param>
		/// <param name="startRowIndex">Start Row Index</param>
		/// <param name="pageSize">PageSize</param>
		/// <param name="totalRows">Total rows</param>
        /// <returns>The retrieved collection of AllowedStore objects.</returns>
        protected static EntityList<AllowedStore> GetAllowedStores(string orderBy, int startRowIndex, int pageSize, out long totalRows)
        {
            return GetList<AllowedStore>(SelectFieldList, "FROM [dbo].[AllowedStores]", new List<SqlParameter>(),orderBy,  startRowIndex, pageSize, out totalRows);
        }

		/// <summary>
        /// Gets a collection AllowedStore objects.
        /// </summary>
		/// <param name="startRowIndex">Start Row Index</param>
		/// <param name="pageSize">Page Size</param>
		/// <param name="totalRows">Total rows</param>
        /// <returns>The retrieved collection of AllowedStore objects.</returns>
        public static EntityList<AllowedStore> GetAllowedStores(int startRowIndex, int pageSize, out long totalRows)
        {
            return GetList<AllowedStore>(SelectFieldList, "FROM [dbo].[AllowedStores]", new List<SqlParameter>(), null,  startRowIndex, pageSize, out totalRows);
        }
		
		/// <summary>
		/// Gets a collection AllowedStore objects by custom where clause.
		/// </summary>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameter">The parameter that is in the where clause</param>
		/// <param name="orderBy">the order by clause. Should start with "order by"</param>
		/// <returns>The retrieved collection of AllowedStore objects.</returns>
		protected static EntityList<AllowedStore> GetAllowedStores(string where, SqlParameter parameter, string orderBy)
		{
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			parameters.Add(parameter);
						
			return GetAllowedStores(string.Empty, where, parameters, orderBy);
		}
		
		/// <summary>
		/// Gets a collection AllowedStore objects by custom where clause.
		/// </summary>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameter">The parameter that is in the where clause</param>
		/// <returns>The retrieved collection of AllowedStore objects.</returns>
		protected static EntityList<AllowedStore> GetAllowedStores(string where, SqlParameter parameter)
		{
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			parameters.Add(parameter);
						
			return GetAllowedStores(string.Empty, where, parameters, AllowedStore.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection AllowedStore objects by custom where clause.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameter">The parameter that is in the where clause</param>
		/// <returns>The retrieved collection of AllowedStore objects.</returns>
		protected static EntityList<AllowedStore> GetAllowedStores(string prefix, string where, SqlParameter parameter)
		{
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			parameters.Add(parameter);
						
			return GetAllowedStores(prefix, where, parameters, AllowedStore.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection AllowedStore objects by custom where clause.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameters">The parameters that are listed in the where clause</param>
		/// <returns>The retrieved collection of AllowedStore objects.</returns>
		protected static EntityList<AllowedStore> GetAllowedStores(string where, System.Collections.Generic.List<SqlParameter> parameters)
		{
			return GetAllowedStores(string.Empty, where, parameters, AllowedStore.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection AllowedStore objects by custom where clause.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameters">The parameters that are listed in the where clause</param>
		/// <returns>The retrieved collection of AllowedStore objects.</returns>
		protected static EntityList<AllowedStore> GetAllowedStores(string prefix, string where, System.Collections.Generic.List<SqlParameter> parameters)
		{
			return GetAllowedStores(prefix, where, parameters, AllowedStore.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection AllowedStore objects by custom where clause and order by.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameters">The parameters that are listed in the where clause</param>
		/// <param name="orderBy">the order by clause. Shoudl start with "order by"</param>
		/// <returns>The retrieved collection of AllowedStore objects.</returns>
		protected static EntityList<AllowedStore> GetAllowedStores(string prefix, string where, System.Collections.Generic.List<SqlParameter> parameters, string orderBy)
		{
			string commandText = @"SELECT " + prefix + "" + AllowedStore.SelectFieldList + "FROM [dbo].[AllowedStores] " + where + " " + orderBy;			
			
			using (SqlHelper helper = new SqlHelper()) 
			{
				using (IDataReader reader = helper.ExecuteDataReader(commandText, CommandType.Text, parameters))
				{
					return EntityBase.InitializeList<AllowedStore>(reader);
				}
			}
		}		
		
		/// <summary>
        /// Gets a collection Address objects.
        /// </summary>
		/// <param name="orderBy">order by</param>
		/// <param name="where">where</param>
		/// <param name=parameters">parameters</param>
		/// <param name="startRowIndex">Start Row Index</param>
		/// <param name="pageSize">PageSize</param>
		/// <param name="totalRows">Total rows</param>
        /// <returns>The retrieved collection of Address objects.</returns>
        protected static EntityList<AllowedStore> GetAllowedStores(string orderBy, string where, System.Collections.Generic.List<SqlParameter> parameters, int startRowIndex, int pageSize, out long totalRows)
        {
            return GetList<AllowedStore>(SelectFieldList, "FROM [dbo].[AllowedStores] " + where, parameters, orderBy, startRowIndex, pageSize, out totalRows);			
		}
		
		/// <summary>
		/// Gets a collection of AllowedStore objects by a Company object.
		/// </summary>
		/// <param name="customer_">customer_</param>
		/// <returns>A collection AllowedStore objects.</returns>
		public static EntityList<AllowedStore> GetAllowedStoresBycustomer_(Company @customer_) 
		{
			string commandText = "AllowedStoreGetByCompany";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@customer_id", @customer_.company_id));
			
			return GetList<AllowedStore>(@customer_, commandText, parameters);
		}
  

		/// <summary>
		/// Gets a collection of AllowedStore objects by a Company object.
		/// </summary>
		/// <param name="company">company</param>
        /// <param name="orderBy"></param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection AllowedStore objects.</returns>
		protected static EntityList<AllowedStore> GetAllowedStoresBycustomer_(Company @customer_, string orderBy, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[AllowedStores] 
WHERE 
	[AllowedStores].[customer_id] = @customer_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
				
			parameters.Add(new SqlParameter("@customer_id", @customer_.company_id));
			
			return GetList<AllowedStore>(SelectFieldList, commandText, parameters, orderBy, startRowIndex, pageSize, out totalRows);
		}

	    /// <summary>
		/// Gets a collection of AllowedStore objects by a Company object.
		/// </summary>
		/// <param name="company_id">company_id</param>
        /// <param name="orderBy"></param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection AllowedStore objects.</returns>
		protected static EntityList<AllowedStore> GetAllowedStoresBycustomer_(int @company_id, string orderBy, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[AllowedStores] 
WHERE 
	[AllowedStores].[customer_id] = @customer_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@customer_id", @company_id));
			
			return GetList<AllowedStore>(SelectFieldList, commandText, parameters, orderBy, startRowIndex, pageSize, out totalRows);
		}		
		
		
		/// <summary>
		/// Gets a collection of AllowedStore objects by a Company object.
		/// </summary>
		/// <param name="company">company</param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection AllowedStore objects.</returns>
		public static EntityList<AllowedStore> GetAllowedStoresBycustomer_(Company @customer_, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[AllowedStores] 
WHERE 
	[AllowedStores].[customer_id] = @customer_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
				
			parameters.Add(new SqlParameter("@customer_id", @customer_.company_id));
			
			return GetList<AllowedStore>(SelectFieldList, commandText, parameters, null, startRowIndex, pageSize, out totalRows);
		}

	    /// <summary>
		/// Gets a collection of AllowedStore objects by a Company object.
		/// </summary>
		/// <param name="company_id">company_id</param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection AllowedStore objects.</returns>
		public static EntityList<AllowedStore> GetAllowedStoresBycustomer_(int @company_id, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[AllowedStores] 
WHERE 
	[AllowedStores].[customer_id] = @customer_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@customer_id", @company_id));
			
			return GetList<AllowedStore>(SelectFieldList, commandText, parameters, null, startRowIndex, pageSize, out totalRows);
		}
		
	
		/// <summary>
		/// Gets a collection of AllowedStore objects by a Company unique identifier.
		/// </summary>
		/// <param name="company_id">company_id</param>
		/// <returns>A collection AllowedStore objects.</returns>
		public static EntityList<AllowedStore> GetAllowedStoresBycustomer_(int @company_id) 
		{
			string commandText = "AllowedStoreGetByCompany";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@customer_id", @company_id));
			
			return GetList<AllowedStore>(commandText, parameters);
		}

		/// <summary>
		/// Create a new AllowedStore object from a Company object.
		/// </summary>
		/// <param name="customer_">customer_</param>
		/// <returns>The newly created AllowedStore object.</returns>
		public static AllowedStore CreateAllowedStoreBycustomer_(Company @customer_)
		{
			AllowedStore allowedStore = InitializeNew<AllowedStore>();
			
			allowedStore.customer_id = @customer_.company_id;
			
			allowedStore.customer_ = @customer_;
			
			return allowedStore;
		}
		
		/// <summary>
		/// Deletes AllowedStore objects by a Company object.
		/// </summary>
		/// <param name="company">company</param>
		public static void DeleteAllowedStoresBycustomer_(Company company) 
		{
			string commandText = "AllowedStoreDeleteByCompany";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@customer_id", company.company_id));
			
			using (SqlHelper helper = new SqlHelper()) 
			{
				helper.Execute(commandText, CommandType.StoredProcedure, parameters);
			}
		}
		
		/// <summary>
		/// Deletes AllowedStore objects by a Company unique identifier.
		/// </summary>
		/// <param name="company_id">company_id</param>
		public static void DeleteAllowedStoresBycustomer_(int company_id) 
		{
			string commandText = "AllowedStoreDeleteByCompany";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@customer_id", company_id));
			
			using (SqlHelper helper = new SqlHelper()) 
			{
				helper.Execute(commandText, CommandType.StoredProcedure, parameters);
			}
		}
		/// <summary>
		/// Gets a collection of AllowedStore objects by a Company object.
		/// </summary>
		/// <param name="supplier_">supplier_</param>
		/// <returns>A collection AllowedStore objects.</returns>
		public static EntityList<AllowedStore> GetAllowedStoresBysupplier_(Company @supplier_) 
		{
			string commandText = "AllowedStoreGetByCompany";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@supplier_id", @supplier_.company_id));
			
			return GetList<AllowedStore>(@supplier_, commandText, parameters);
		}
  

		/// <summary>
		/// Gets a collection of AllowedStore objects by a Company object.
		/// </summary>
		/// <param name="company">company</param>
        /// <param name="orderBy"></param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection AllowedStore objects.</returns>
		protected static EntityList<AllowedStore> GetAllowedStoresBysupplier_(Company @supplier_, string orderBy, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[AllowedStores] 
WHERE 
	[AllowedStores].[supplier_id] = @supplier_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
				
			parameters.Add(new SqlParameter("@supplier_id", @supplier_.company_id));
			
			return GetList<AllowedStore>(SelectFieldList, commandText, parameters, orderBy, startRowIndex, pageSize, out totalRows);
		}

	    /// <summary>
		/// Gets a collection of AllowedStore objects by a Company object.
		/// </summary>
		/// <param name="company_id">company_id</param>
        /// <param name="orderBy"></param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection AllowedStore objects.</returns>
		protected static EntityList<AllowedStore> GetAllowedStoresBysupplier_(int @company_id, string orderBy, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[AllowedStores] 
WHERE 
	[AllowedStores].[supplier_id] = @supplier_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@supplier_id", @company_id));
			
			return GetList<AllowedStore>(SelectFieldList, commandText, parameters, orderBy, startRowIndex, pageSize, out totalRows);
		}		
		
		
		/// <summary>
		/// Gets a collection of AllowedStore objects by a Company object.
		/// </summary>
		/// <param name="company">company</param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection AllowedStore objects.</returns>
		public static EntityList<AllowedStore> GetAllowedStoresBysupplier_(Company @supplier_, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[AllowedStores] 
WHERE 
	[AllowedStores].[supplier_id] = @supplier_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
				
			parameters.Add(new SqlParameter("@supplier_id", @supplier_.company_id));
			
			return GetList<AllowedStore>(SelectFieldList, commandText, parameters, null, startRowIndex, pageSize, out totalRows);
		}

	    /// <summary>
		/// Gets a collection of AllowedStore objects by a Company object.
		/// </summary>
		/// <param name="company_id">company_id</param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection AllowedStore objects.</returns>
		public static EntityList<AllowedStore> GetAllowedStoresBysupplier_(int @company_id, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[AllowedStores] 
WHERE 
	[AllowedStores].[supplier_id] = @supplier_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@supplier_id", @company_id));
			
			return GetList<AllowedStore>(SelectFieldList, commandText, parameters, null, startRowIndex, pageSize, out totalRows);
		}
		
	
		/// <summary>
		/// Gets a collection of AllowedStore objects by a Company unique identifier.
		/// </summary>
		/// <param name="company_id">company_id</param>
		/// <returns>A collection AllowedStore objects.</returns>
		public static EntityList<AllowedStore> GetAllowedStoresBysupplier_(int @company_id) 
		{
			string commandText = "AllowedStoreGetByCompany";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@supplier_id", @company_id));
			
			return GetList<AllowedStore>(commandText, parameters);
		}

		/// <summary>
		/// Create a new AllowedStore object from a Company object.
		/// </summary>
		/// <param name="supplier_">supplier_</param>
		/// <returns>The newly created AllowedStore object.</returns>
		public static AllowedStore CreateAllowedStoreBysupplier_(Company @supplier_)
		{
			AllowedStore allowedStore = InitializeNew<AllowedStore>();
			
			allowedStore.supplier_id = @supplier_.company_id;
			
			allowedStore.supplier_ = @supplier_;
			
			return allowedStore;
		}
		
		/// <summary>
		/// Deletes AllowedStore objects by a Company object.
		/// </summary>
		/// <param name="company">company</param>
		public static void DeleteAllowedStoresBysupplier_(Company company) 
		{
			string commandText = "AllowedStoreDeleteByCompany";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@supplier_id", company.company_id));
			
			using (SqlHelper helper = new SqlHelper()) 
			{
				helper.Execute(commandText, CommandType.StoredProcedure, parameters);
			}
		}
		
		/// <summary>
		/// Deletes AllowedStore objects by a Company unique identifier.
		/// </summary>
		/// <param name="company_id">company_id</param>
		public static void DeleteAllowedStoresBysupplier_(int company_id) 
		{
			string commandText = "AllowedStoreDeleteByCompany";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@supplier_id", company_id));
			
			using (SqlHelper helper = new SqlHelper()) 
			{
				helper.Execute(commandText, CommandType.StoredProcedure, parameters);
			}
		}
		#endregion
		
		#region Subclasses
		public static partial class AllowedStoreProperties
		{
			public const string entry_id = "entry_id";
			public const string customer_id = "customer_id";
			public const string supplier_id = "supplier_id";
			public const string account_number = "account_number";
			public const string is_member = "is_member";
			public const string authoriser_email = "authoriser_email";
			public const string creation_datetime = "creation_datetime";
		}
		#endregion
	}
}
