/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 10/08/2012 7:49:05 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;

using HealthStop.Business.Framework;


namespace HealthStop.Business
{
	/// <summary>
	/// This object represents the properties and methods of a SupplierProduct.
	/// </summary>
	[Serializable()]
	[DebuggerDisplay("company_id: {company_id}, product_code: {product_code}")]
	public partial class SupplierProduct
	{
		#region Public Properties
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private int _company_id = int.MinValue;
		/// <summary>
		/// company_id
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(true, false, false)]
		public int company_id
		{
			[DebuggerStepThrough()]
			get { return this._company_id; }
			set 
			{
				if (this._company_id != value) 
				{
					this._company_id = value;
					this.IsDirty = true;	
					OnPropertyChanged("company_id");
					this._company_ = null;
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private string _product_code = String.Empty;
		/// <summary>
		/// product_code
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(true, false, false)]
		public string product_code
		{
			[DebuggerStepThrough()]
			get { return this._product_code; }
			set 
			{
				if (this._product_code != value) 
				{
					this._product_code = value;
					this.IsDirty = true;	
					OnPropertyChanged("product_code");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private string _barcode = String.Empty;
		/// <summary>
		/// barcode
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, false)]
		public string barcode
		{
			[DebuggerStepThrough()]
			get { return this._barcode; }
			set 
			{
				if (this._barcode != value) 
				{
					this._barcode = value;
					this.IsDirty = true;	
					OnPropertyChanged("barcode");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private string _department = String.Empty;
		/// <summary>
		/// department
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, true)]
		public string department
		{
			[DebuggerStepThrough()]
			get { return this._department; }
			set 
			{
				if (this._department != value) 
				{
					this._department = value;
					this.IsDirty = true;	
					OnPropertyChanged("department");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private string _brand = String.Empty;
		/// <summary>
		/// brand
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, true)]
		public string brand
		{
			[DebuggerStepThrough()]
			get { return this._brand; }
			set 
			{
				if (this._brand != value) 
				{
					this._brand = value;
					this.IsDirty = true;	
					OnPropertyChanged("brand");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private string _description = String.Empty;
		/// <summary>
		/// description
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, true)]
		public string description
		{
			[DebuggerStepThrough()]
			get { return this._description; }
			set 
			{
				if (this._description != value) 
				{
					this._description = value;
					this.IsDirty = true;	
					OnPropertyChanged("description");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private decimal _rRP = decimal.MinValue;
		/// <summary>
		/// RRP
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, true)]
		public decimal RRP
		{
			[DebuggerStepThrough()]
			get { return this._rRP; }
			set 
			{
				if (this._rRP != value) 
				{
					this._rRP = value;
					this.IsDirty = true;	
					OnPropertyChanged("RRP");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private bool _is_GST = false;
		/// <summary>
		/// is_GST
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, false)]
		public bool is_GST
		{
			[DebuggerStepThrough()]
			get { return this._is_GST; }
			set 
			{
				if (this._is_GST != value) 
				{
					this._is_GST = value;
					this.IsDirty = true;	
					OnPropertyChanged("is_GST");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private bool _is_available = false;
		/// <summary>
		/// is_available
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, false)]
		public bool is_available
		{
			[DebuggerStepThrough()]
			get { return this._is_available; }
			set 
			{
				if (this._is_available != value) 
				{
					this._is_available = value;
					this.IsDirty = true;	
					OnPropertyChanged("is_available");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private string _picture_url = String.Empty;
		/// <summary>
		/// picture_url
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, true)]
		public string picture_url
		{
			[DebuggerStepThrough()]
			get { return this._picture_url; }
			set 
			{
				if (this._picture_url != value) 
				{
					this._picture_url = value;
					this.IsDirty = true;	
					OnPropertyChanged("picture_url");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private string _info_url = String.Empty;
		/// <summary>
		/// info_url
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, true)]
		public string info_url
		{
			[DebuggerStepThrough()]
			get { return this._info_url; }
			set 
			{
				if (this._info_url != value) 
				{
					this._info_url = value;
					this.IsDirty = true;	
					OnPropertyChanged("info_url");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private decimal _wholesale_price = decimal.MinValue;
		/// <summary>
		/// wholesale_price
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, false)]
		public decimal wholesale_price
		{
			[DebuggerStepThrough()]
			get { return this._wholesale_price; }
			set 
			{
				if (this._wholesale_price != value) 
				{
					this._wholesale_price = value;
					this.IsDirty = true;	
					OnPropertyChanged("wholesale_price");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private decimal _member_price = decimal.MinValue;
		/// <summary>
		/// member_price
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, true)]
		public decimal member_price
		{
			[DebuggerStepThrough()]
			get { return this._member_price; }
			set 
			{
				if (this._member_price != value) 
				{
					this._member_price = value;
					this.IsDirty = true;	
					OnPropertyChanged("member_price");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private double _range1_min_quantity;
		/// <summary>
		/// range1_min_quantity
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, true)]
		public double range1_min_quantity
		{
			[DebuggerStepThrough()]
			get { return this._range1_min_quantity; }
			set 
			{
				if (this._range1_min_quantity != value) 
				{
					this._range1_min_quantity = value;
					this.IsDirty = true;	
					OnPropertyChanged("range1_min_quantity");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private decimal _range1_price = decimal.MinValue;
		/// <summary>
		/// range1_price
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, true)]
		public decimal range1_price
		{
			[DebuggerStepThrough()]
			get { return this._range1_price; }
			set 
			{
				if (this._range1_price != value) 
				{
					this._range1_price = value;
					this.IsDirty = true;	
					OnPropertyChanged("range1_price");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private double _range2_min_quantity;
		/// <summary>
		/// range2_min_quantity
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, true)]
		public double range2_min_quantity
		{
			[DebuggerStepThrough()]
			get { return this._range2_min_quantity; }
			set 
			{
				if (this._range2_min_quantity != value) 
				{
					this._range2_min_quantity = value;
					this.IsDirty = true;	
					OnPropertyChanged("range2_min_quantity");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private decimal _range2_price = decimal.MinValue;
		/// <summary>
		/// range2_price
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, true)]
		public decimal range2_price
		{
			[DebuggerStepThrough()]
			get { return this._range2_price; }
			set 
			{
				if (this._range2_price != value) 
				{
					this._range2_price = value;
					this.IsDirty = true;	
					OnPropertyChanged("range2_price");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private double _range3_min_quantity;
		/// <summary>
		/// range3_min_quantity
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, true)]
		public double range3_min_quantity
		{
			[DebuggerStepThrough()]
			get { return this._range3_min_quantity; }
			set 
			{
				if (this._range3_min_quantity != value) 
				{
					this._range3_min_quantity = value;
					this.IsDirty = true;	
					OnPropertyChanged("range3_min_quantity");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private decimal _range3_price = decimal.MinValue;
		/// <summary>
		/// range3_price
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, true)]
		public decimal range3_price
		{
			[DebuggerStepThrough()]
			get { return this._range3_price; }
			set 
			{
				if (this._range3_price != value) 
				{
					this._range3_price = value;
					this.IsDirty = true;	
					OnPropertyChanged("range3_price");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private DateTime _lastupdated_datetime = DateTime.MinValue;
		/// <summary>
		/// lastupdated_datetime
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, false)]
		public DateTime lastupdated_datetime
		{
			[DebuggerStepThrough()]
			get { return this._lastupdated_datetime; }
			set 
			{
				if (this._lastupdated_datetime != value) 
				{
					this._lastupdated_datetime = value;
					this.IsDirty = true;	
					OnPropertyChanged("lastupdated_datetime");
				}
			}
		}
		
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private Company _company_ = null;
		/// <summary>
		/// The parent Company object
		/// </summary>
		public Company company_
		{
			get 
			{
				if (_company_ == null) 
				{
					_company_ = GetParentEntity(Company.GetCompany(this.company_id)) as Company;
				}
				return _company_;
			}
			set
			{
				if(_company_ != value) 
				{
					_company_ = value;
					
					if (value != null) 
					{
						this.company_id = value.company_id;
					}
					else 
					{
						this.company_id = int.MinValue;
					}
				}
			}
		}
		
		
		#endregion
		
		#region Non-Public Properties
		/// <summary>
		/// Gets the SQL statement for an insert
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		protected override string InsertSPName
		{
			get 
			{
				return typeof(SupplierProduct).Name + "Insert";
			}
		}
		
		/// <summary>
		/// Gets the SQL statement for an update by key
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		protected override string UpdateSPName
		{
			get
			{
				return typeof(SupplierProduct).Name + "Update";
			}
		}
		
		/// <summary>
		/// Gets the SQL statement for a delete by key
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		protected override string DeleteSPName
		{
			get
			{
				return typeof(SupplierProduct).Name + "Delete";
			}
		}
		#endregion
		
		#region Constructors
		/// <summary>
		/// The default protected constructor
		/// </summary>
		protected SupplierProduct() { }
		#endregion
		
		#region Public Methods
		

        /// <summary>
        /// Refreshes the entity with data from the data source. Child entity objects and entity list objects will be preserved (ie. they will not be replaced with new objects so that references to them are retained, such as bound data controls).
        /// </summary>
        public override void Refresh()
		{
			this.Replace(GetSupplierProduct(this.company_id, this.product_code));
		}

		#endregion
		
		#region Non-Public Methods
		/// <summary>
		/// This is called before an entity is saved to ensure that any parent entities keys are set properly
		/// </summary>
		protected override void EnsureParentProperties()
		{
			if (_company_ != null)
			{	
				this.company_id = this.company_.company_id;
			}
			
		}
		#endregion
		
		#region Static Properties
		/// <summary>
		/// A list of all fields for this entity in the database. It does not include the 
		/// select keyword, or the table information - just the fields. This can be used
		/// for new dynamic methods.
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		public static string SelectFieldList 
		{
			get 
			{
				return @"
	[SupplierProducts].[company_id],
	[SupplierProducts].[product_code],
	[SupplierProducts].[barcode],
	[SupplierProducts].[department],
	[SupplierProducts].[brand],
	[SupplierProducts].[description],
	[SupplierProducts].[RRP],
	[SupplierProducts].[is_GST],
	[SupplierProducts].[is_available],
	[SupplierProducts].[picture_url],
	[SupplierProducts].[info_url],
	[SupplierProducts].[wholesale_price],
	[SupplierProducts].[member_price],
	[SupplierProducts].[range1_min_quantity],
	[SupplierProducts].[range1_price],
	[SupplierProducts].[range2_min_quantity],
	[SupplierProducts].[range2_price],
	[SupplierProducts].[range3_min_quantity],
	[SupplierProducts].[range3_price],
	[SupplierProducts].[lastupdated_datetime]
";
			}
		}
		
		
		/// <summary>
        /// Table Name
        /// </summary>
        public new static string TableName
        {
            get
            {
                return "SupplierProducts";
            }
        }

		#endregion
		
		#region Static Methods
		/// <summary>
		/// Insert a SupplierProduct into the data store based on the primitive properties. This can be used as the 
		/// insert method for an ObjectDataSource.
		/// </summary>
		/// <param name="company_id">company_id</param>
		/// <param name="product_code">product_code</param>
		/// <param name="barcode">barcode</param>
		/// <param name="department">department</param>
		/// <param name="brand">brand</param>
		/// <param name="description">description</param>
		/// <param name="rRP">rRP</param>
		/// <param name="is_GST">is_GST</param>
		/// <param name="is_available">is_available</param>
		/// <param name="picture_url">picture_url</param>
		/// <param name="info_url">info_url</param>
		/// <param name="wholesale_price">wholesale_price</param>
		/// <param name="member_price">member_price</param>
		/// <param name="range1_min_quantity">range1_min_quantity</param>
		/// <param name="range1_price">range1_price</param>
		/// <param name="range2_min_quantity">range2_min_quantity</param>
		/// <param name="range2_price">range2_price</param>
		/// <param name="range3_min_quantity">range3_min_quantity</param>
		/// <param name="range3_price">range3_price</param>
		/// <param name="lastupdated_datetime">lastupdated_datetime</param>
		public static void InsertSupplierProduct(int @company_id, string @product_code, string @barcode, string @department, string @brand, string @description, decimal @rRP, bool @is_GST, bool @is_available, string @picture_url, string @info_url, decimal @wholesale_price, decimal @member_price, double @range1_min_quantity, decimal @range1_price, double @range2_min_quantity, decimal @range2_price, double @range3_min_quantity, decimal @range3_price, DateTime @lastupdated_datetime)
		{
            using (SqlHelper helper = new SqlHelper())
            {
                try
                {
                    helper.BeginTransaction();
            		InsertSupplierProduct(@company_id, @product_code, @barcode, @department, @brand, @description, @rRP, @is_GST, @is_available, @picture_url, @info_url, @wholesale_price, @member_price, @range1_min_quantity, @range1_price, @range2_min_quantity, @range2_price, @range3_min_quantity, @range3_price, @lastupdated_datetime, helper);
                    helper.Commit();
                }
                catch
                {
                    helper.Rollback();
                    throw;
                }
            }
		}

		/// <summary>
		/// Insert a SupplierProduct into the data store based on the primitive properties. This can be used as the 
		/// insert method for an ObjectDataSource.
		/// </summary>
		/// <param name="company_id">company_id</param>
		/// <param name="product_code">product_code</param>
		/// <param name="barcode">barcode</param>
		/// <param name="department">department</param>
		/// <param name="brand">brand</param>
		/// <param name="description">description</param>
		/// <param name="rRP">rRP</param>
		/// <param name="is_GST">is_GST</param>
		/// <param name="is_available">is_available</param>
		/// <param name="picture_url">picture_url</param>
		/// <param name="info_url">info_url</param>
		/// <param name="wholesale_price">wholesale_price</param>
		/// <param name="member_price">member_price</param>
		/// <param name="range1_min_quantity">range1_min_quantity</param>
		/// <param name="range1_price">range1_price</param>
		/// <param name="range2_min_quantity">range2_min_quantity</param>
		/// <param name="range2_price">range2_price</param>
		/// <param name="range3_min_quantity">range3_min_quantity</param>
		/// <param name="range3_price">range3_price</param>
		/// <param name="lastupdated_datetime">lastupdated_datetime</param>
		/// <param name="helper">helper</param>
		internal static void InsertSupplierProduct(int @company_id, string @product_code, string @barcode, string @department, string @brand, string @description, decimal @rRP, bool @is_GST, bool @is_available, string @picture_url, string @info_url, decimal @wholesale_price, decimal @member_price, double @range1_min_quantity, decimal @range1_price, double @range2_min_quantity, decimal @range2_price, double @range3_min_quantity, decimal @range3_price, DateTime @lastupdated_datetime, SqlHelper @helper)
		{
			string commandText = "SupplierProductInsert";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@company_id", EntityBase.GetDatabaseValue(@company_id)));
			parameters.Add(new SqlParameter("@product_code", EntityBase.GetDatabaseValue(@product_code)));
			parameters.Add(new SqlParameter("@barcode", EntityBase.GetDatabaseValue(@barcode)));
			parameters.Add(new SqlParameter("@department", EntityBase.GetDatabaseValue(@department)));
			parameters.Add(new SqlParameter("@brand", EntityBase.GetDatabaseValue(@brand)));
			parameters.Add(new SqlParameter("@description", EntityBase.GetDatabaseValue(@description)));
			parameters.Add(new SqlParameter("@RRP", EntityBase.GetDatabaseValue(@rRP)));
			parameters.Add(new SqlParameter("@is_GST", @is_GST));
			parameters.Add(new SqlParameter("@is_available", @is_available));
			parameters.Add(new SqlParameter("@picture_url", EntityBase.GetDatabaseValue(@picture_url)));
			parameters.Add(new SqlParameter("@info_url", EntityBase.GetDatabaseValue(@info_url)));
			parameters.Add(new SqlParameter("@wholesale_price", EntityBase.GetDatabaseValue(@wholesale_price)));
			parameters.Add(new SqlParameter("@member_price", EntityBase.GetDatabaseValue(@member_price)));
			parameters.Add(new SqlParameter("@range1_min_quantity", @range1_min_quantity));
			parameters.Add(new SqlParameter("@range1_price", EntityBase.GetDatabaseValue(@range1_price)));
			parameters.Add(new SqlParameter("@range2_min_quantity", @range2_min_quantity));
			parameters.Add(new SqlParameter("@range2_price", EntityBase.GetDatabaseValue(@range2_price)));
			parameters.Add(new SqlParameter("@range3_min_quantity", @range3_min_quantity));
			parameters.Add(new SqlParameter("@range3_price", EntityBase.GetDatabaseValue(@range3_price)));
			parameters.Add(new SqlParameter("@lastupdated_datetime", EntityBase.GetDatabaseValue(@lastupdated_datetime)));
			
			@helper.Execute(commandText, CommandType.StoredProcedure, parameters);
		}
		
		/// <summary>
		/// Updates a SupplierProduct into the data store based on the primitive properties. This can be used as the 
		/// update method for an ObjectDataSource.
		/// </summary>
		/// <param name="company_id">company_id</param>
		/// <param name="product_code">product_code</param>
		/// <param name="barcode">barcode</param>
		/// <param name="department">department</param>
		/// <param name="brand">brand</param>
		/// <param name="description">description</param>
		/// <param name="rRP">rRP</param>
		/// <param name="is_GST">is_GST</param>
		/// <param name="is_available">is_available</param>
		/// <param name="picture_url">picture_url</param>
		/// <param name="info_url">info_url</param>
		/// <param name="wholesale_price">wholesale_price</param>
		/// <param name="member_price">member_price</param>
		/// <param name="range1_min_quantity">range1_min_quantity</param>
		/// <param name="range1_price">range1_price</param>
		/// <param name="range2_min_quantity">range2_min_quantity</param>
		/// <param name="range2_price">range2_price</param>
		/// <param name="range3_min_quantity">range3_min_quantity</param>
		/// <param name="range3_price">range3_price</param>
		/// <param name="lastupdated_datetime">lastupdated_datetime</param>
		public static void UpdateSupplierProduct(int @company_id, string @product_code, string @barcode, string @department, string @brand, string @description, decimal @rRP, bool @is_GST, bool @is_available, string @picture_url, string @info_url, decimal @wholesale_price, decimal @member_price, double @range1_min_quantity, decimal @range1_price, double @range2_min_quantity, decimal @range2_price, double @range3_min_quantity, decimal @range3_price, DateTime @lastupdated_datetime)
		{
			using (SqlHelper helper = new SqlHelper()) 
			{
				try
				{
					helper.BeginTransaction();
					UpdateSupplierProduct(@company_id, @product_code, @barcode, @department, @brand, @description, @rRP, @is_GST, @is_available, @picture_url, @info_url, @wholesale_price, @member_price, @range1_min_quantity, @range1_price, @range2_min_quantity, @range2_price, @range3_min_quantity, @range3_price, @lastupdated_datetime, helper);
					helper.Commit();
				}
				catch 
				{
					helper.Rollback();	
					throw;
				}
			}
		}
		
		/// <summary>
		/// Updates a SupplierProduct into the data store based on the primitive properties. This can be used as the 
		/// update method for an ObjectDataSource.
		/// </summary>
		/// <param name="company_id">company_id</param>
		/// <param name="product_code">product_code</param>
		/// <param name="barcode">barcode</param>
		/// <param name="department">department</param>
		/// <param name="brand">brand</param>
		/// <param name="description">description</param>
		/// <param name="rRP">rRP</param>
		/// <param name="is_GST">is_GST</param>
		/// <param name="is_available">is_available</param>
		/// <param name="picture_url">picture_url</param>
		/// <param name="info_url">info_url</param>
		/// <param name="wholesale_price">wholesale_price</param>
		/// <param name="member_price">member_price</param>
		/// <param name="range1_min_quantity">range1_min_quantity</param>
		/// <param name="range1_price">range1_price</param>
		/// <param name="range2_min_quantity">range2_min_quantity</param>
		/// <param name="range2_price">range2_price</param>
		/// <param name="range3_min_quantity">range3_min_quantity</param>
		/// <param name="range3_price">range3_price</param>
		/// <param name="lastupdated_datetime">lastupdated_datetime</param>
		/// <param name="helper">helper</param>
		internal static void UpdateSupplierProduct(int @company_id, string @product_code, string @barcode, string @department, string @brand, string @description, decimal @rRP, bool @is_GST, bool @is_available, string @picture_url, string @info_url, decimal @wholesale_price, decimal @member_price, double @range1_min_quantity, decimal @range1_price, double @range2_min_quantity, decimal @range2_price, double @range3_min_quantity, decimal @range3_price, DateTime @lastupdated_datetime, SqlHelper @helper)
		{
			string commandText = "SupplierProductUpdate";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@company_id", EntityBase.GetDatabaseValue(@company_id)));
			parameters.Add(new SqlParameter("@product_code", EntityBase.GetDatabaseValue(@product_code)));
			parameters.Add(new SqlParameter("@barcode", EntityBase.GetDatabaseValue(@barcode)));
			parameters.Add(new SqlParameter("@department", EntityBase.GetDatabaseValue(@department)));
			parameters.Add(new SqlParameter("@brand", EntityBase.GetDatabaseValue(@brand)));
			parameters.Add(new SqlParameter("@description", EntityBase.GetDatabaseValue(@description)));
			parameters.Add(new SqlParameter("@RRP", EntityBase.GetDatabaseValue(@rRP)));
			parameters.Add(new SqlParameter("@is_GST", @is_GST));
			parameters.Add(new SqlParameter("@is_available", @is_available));
			parameters.Add(new SqlParameter("@picture_url", EntityBase.GetDatabaseValue(@picture_url)));
			parameters.Add(new SqlParameter("@info_url", EntityBase.GetDatabaseValue(@info_url)));
			parameters.Add(new SqlParameter("@wholesale_price", EntityBase.GetDatabaseValue(@wholesale_price)));
			parameters.Add(new SqlParameter("@member_price", EntityBase.GetDatabaseValue(@member_price)));
			parameters.Add(new SqlParameter("@range1_min_quantity", @range1_min_quantity));
			parameters.Add(new SqlParameter("@range1_price", EntityBase.GetDatabaseValue(@range1_price)));
			parameters.Add(new SqlParameter("@range2_min_quantity", @range2_min_quantity));
			parameters.Add(new SqlParameter("@range2_price", EntityBase.GetDatabaseValue(@range2_price)));
			parameters.Add(new SqlParameter("@range3_min_quantity", @range3_min_quantity));
			parameters.Add(new SqlParameter("@range3_price", EntityBase.GetDatabaseValue(@range3_price)));
			parameters.Add(new SqlParameter("@lastupdated_datetime", EntityBase.GetDatabaseValue(@lastupdated_datetime)));
			
			@helper.Execute(commandText, CommandType.StoredProcedure, parameters);
		}
		
		/// <summary>
		/// Deletes a SupplierProduct from the data store based on the primitive primary keys. This can be used as the 
		/// delete method for an ObjectDataSource.
		/// </summary>
		/// <param name="company_id">company_id</param>
		/// <param name="product_code">product_code</param>
		public static void DeleteSupplierProduct(int @company_id, string @product_code)
		{
			using (SqlHelper helper = new SqlHelper()) 
			{
				try 
				{
					helper.BeginTransaction();
					DeleteSupplierProduct(@company_id, @product_code, helper);
					helper.Commit();
				} 
				catch 
				{
					helper.Rollback();
					throw;
				}
			}
		}
		
		/// <summary>
		/// Deletes a SupplierProduct from the data store based on the primitive primary keys. This can be used as the 
		/// delete method for an ObjectDataSource.
		/// </summary>
		/// <param name="company_id">company_id</param>
		/// <param name="product_code">product_code</param>
		/// <param name="helper">helper</param>
		internal static void DeleteSupplierProduct(int @company_id, string @product_code, SqlHelper @helper)
		{
			string commandText = "SupplierProductDelete";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@company_id", @company_id));
			parameters.Add(new SqlParameter("@product_code", @product_code));
		
			@helper.Execute(commandText, CommandType.StoredProcedure, parameters);
		}
		
		/// <summary>
		/// Creates a new SupplierProduct object.
		/// </summary>
		/// <returns>The newly created SupplierProduct object.</returns>
		public static SupplierProduct CreateSupplierProduct()
		{
			return InitializeNew<SupplierProduct>();
		}
		
		/// <summary>
		/// Retrieve information for a SupplierProduct by a SupplierProduct's unique identifier.
		/// </summary>
		/// <param name="company_id">company_id</param>
		/// <param name="product_code">product_code</param>
		/// <returns>SupplierProduct</returns>
		public static SupplierProduct GetSupplierProduct(int company_id, string product_code)
		{
			string commandText = "SupplierProductGet";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@company_id", company_id));
			parameters.Add(new SqlParameter("@product_code", product_code));
			
			return GetOne<SupplierProduct>(commandText, parameters);
		}
		
		/// <summary>
		/// Gets a collection SupplierProduct objects.
		/// </summary>
		/// <returns>The retrieved collection of SupplierProduct objects.</returns>
		public static EntityList<SupplierProduct> GetSupplierProducts()
		{
			string commandText = "SupplierProductGetAll";
		
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			return GetList<SupplierProduct>(commandText, parameters);
		}
		
		/// <summary>
        /// Gets a collection SupplierProduct objects.
        /// </summary>
		/// <param name="orderBy">order by</param>
		/// <param name="startRowIndex">Start Row Index</param>
		/// <param name="pageSize">PageSize</param>
		/// <param name="totalRows">Total rows</param>
        /// <returns>The retrieved collection of SupplierProduct objects.</returns>
        protected static EntityList<SupplierProduct> GetSupplierProducts(string orderBy, int startRowIndex, int pageSize, out long totalRows)
        {
            return GetList<SupplierProduct>(SelectFieldList, "FROM [dbo].[SupplierProducts]", new List<SqlParameter>(),orderBy,  startRowIndex, pageSize, out totalRows);
        }

		/// <summary>
        /// Gets a collection SupplierProduct objects.
        /// </summary>
		/// <param name="startRowIndex">Start Row Index</param>
		/// <param name="pageSize">Page Size</param>
		/// <param name="totalRows">Total rows</param>
        /// <returns>The retrieved collection of SupplierProduct objects.</returns>
        public static EntityList<SupplierProduct> GetSupplierProducts(int startRowIndex, int pageSize, out long totalRows)
        {
            return GetList<SupplierProduct>(SelectFieldList, "FROM [dbo].[SupplierProducts]", new List<SqlParameter>(), null,  startRowIndex, pageSize, out totalRows);
        }
		
		/// <summary>
		/// Gets a collection SupplierProduct objects by custom where clause.
		/// </summary>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameter">The parameter that is in the where clause</param>
		/// <param name="orderBy">the order by clause. Should start with "order by"</param>
		/// <returns>The retrieved collection of SupplierProduct objects.</returns>
		protected static EntityList<SupplierProduct> GetSupplierProducts(string where, SqlParameter parameter, string orderBy)
		{
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			parameters.Add(parameter);
						
			return GetSupplierProducts(string.Empty, where, parameters, orderBy);
		}
		
		/// <summary>
		/// Gets a collection SupplierProduct objects by custom where clause.
		/// </summary>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameter">The parameter that is in the where clause</param>
		/// <returns>The retrieved collection of SupplierProduct objects.</returns>
		protected static EntityList<SupplierProduct> GetSupplierProducts(string where, SqlParameter parameter)
		{
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			parameters.Add(parameter);
						
			return GetSupplierProducts(string.Empty, where, parameters, SupplierProduct.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection SupplierProduct objects by custom where clause.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameter">The parameter that is in the where clause</param>
		/// <returns>The retrieved collection of SupplierProduct objects.</returns>
		protected static EntityList<SupplierProduct> GetSupplierProducts(string prefix, string where, SqlParameter parameter)
		{
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			parameters.Add(parameter);
						
			return GetSupplierProducts(prefix, where, parameters, SupplierProduct.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection SupplierProduct objects by custom where clause.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameters">The parameters that are listed in the where clause</param>
		/// <returns>The retrieved collection of SupplierProduct objects.</returns>
		protected static EntityList<SupplierProduct> GetSupplierProducts(string where, System.Collections.Generic.List<SqlParameter> parameters)
		{
			return GetSupplierProducts(string.Empty, where, parameters, SupplierProduct.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection SupplierProduct objects by custom where clause.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameters">The parameters that are listed in the where clause</param>
		/// <returns>The retrieved collection of SupplierProduct objects.</returns>
		protected static EntityList<SupplierProduct> GetSupplierProducts(string prefix, string where, System.Collections.Generic.List<SqlParameter> parameters)
		{
			return GetSupplierProducts(prefix, where, parameters, SupplierProduct.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection SupplierProduct objects by custom where clause and order by.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameters">The parameters that are listed in the where clause</param>
		/// <param name="orderBy">the order by clause. Shoudl start with "order by"</param>
		/// <returns>The retrieved collection of SupplierProduct objects.</returns>
		protected static EntityList<SupplierProduct> GetSupplierProducts(string prefix, string where, System.Collections.Generic.List<SqlParameter> parameters, string orderBy)
		{
			string commandText = @"SELECT " + prefix + "" + SupplierProduct.SelectFieldList + "FROM [dbo].[SupplierProducts] " + where + " " + orderBy;			
			
			using (SqlHelper helper = new SqlHelper()) 
			{
				using (IDataReader reader = helper.ExecuteDataReader(commandText, CommandType.Text, parameters))
				{
					return EntityBase.InitializeList<SupplierProduct>(reader);
				}
			}
		}		
		
		/// <summary>
        /// Gets a collection Address objects.
        /// </summary>
		/// <param name="orderBy">order by</param>
		/// <param name="where">where</param>
		/// <param name=parameters">parameters</param>
		/// <param name="startRowIndex">Start Row Index</param>
		/// <param name="pageSize">PageSize</param>
		/// <param name="totalRows">Total rows</param>
        /// <returns>The retrieved collection of Address objects.</returns>
        protected static EntityList<SupplierProduct> GetSupplierProducts(string orderBy, string where, System.Collections.Generic.List<SqlParameter> parameters, int startRowIndex, int pageSize, out long totalRows)
        {
            return GetList<SupplierProduct>(SelectFieldList, "FROM [dbo].[SupplierProducts] " + where, parameters, orderBy, startRowIndex, pageSize, out totalRows);			
		}
		
		/// <summary>
		/// Gets a collection of SupplierProduct objects by a Company object.
		/// </summary>
		/// <param name="company_">company_</param>
		/// <returns>A collection SupplierProduct objects.</returns>
		public static EntityList<SupplierProduct> GetSupplierProductsBycompany_(Company @company_) 
		{
			string commandText = "SupplierProductGetByCompany";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@company_id", @company_.company_id));
			
			return GetList<SupplierProduct>(@company_, commandText, parameters);
		}
  

		/// <summary>
		/// Gets a collection of SupplierProduct objects by a Company object.
		/// </summary>
		/// <param name="company">company</param>
        /// <param name="orderBy"></param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection SupplierProduct objects.</returns>
		protected static EntityList<SupplierProduct> GetSupplierProductsBycompany_(Company @company_, string orderBy, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[SupplierProducts] 
WHERE 
	[SupplierProducts].[company_id] = @company_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
				
			parameters.Add(new SqlParameter("@company_id", @company_.company_id));
			
			return GetList<SupplierProduct>(SelectFieldList, commandText, parameters, orderBy, startRowIndex, pageSize, out totalRows);
		}

	    /// <summary>
		/// Gets a collection of SupplierProduct objects by a Company object.
		/// </summary>
		/// <param name="company_id">company_id</param>
        /// <param name="orderBy"></param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection SupplierProduct objects.</returns>
		protected static EntityList<SupplierProduct> GetSupplierProductsBycompany_(int @company_id, string orderBy, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[SupplierProducts] 
WHERE 
	[SupplierProducts].[company_id] = @company_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@company_id", @company_id));
			
			return GetList<SupplierProduct>(SelectFieldList, commandText, parameters, orderBy, startRowIndex, pageSize, out totalRows);
		}		
		
		
		/// <summary>
		/// Gets a collection of SupplierProduct objects by a Company object.
		/// </summary>
		/// <param name="company">company</param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection SupplierProduct objects.</returns>
		public static EntityList<SupplierProduct> GetSupplierProductsBycompany_(Company @company_, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[SupplierProducts] 
WHERE 
	[SupplierProducts].[company_id] = @company_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
				
			parameters.Add(new SqlParameter("@company_id", @company_.company_id));
			
			return GetList<SupplierProduct>(SelectFieldList, commandText, parameters, null, startRowIndex, pageSize, out totalRows);
		}

	    /// <summary>
		/// Gets a collection of SupplierProduct objects by a Company object.
		/// </summary>
		/// <param name="company_id">company_id</param>
        /// <param name="startRowIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="totalRows"></param>
		/// <returns>A collection SupplierProduct objects.</returns>
		public static EntityList<SupplierProduct> GetSupplierProductsBycompany_(int @company_id, long startRowIndex, int pageSize, out long totalRows) 
		{
			string commandText = @"
FROM 
	[dbo].[SupplierProducts] 
WHERE 
	[SupplierProducts].[company_id] = @company_id ";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@company_id", @company_id));
			
			return GetList<SupplierProduct>(SelectFieldList, commandText, parameters, null, startRowIndex, pageSize, out totalRows);
		}
		
	
		/// <summary>
		/// Gets a collection of SupplierProduct objects by a Company unique identifier.
		/// </summary>
		/// <param name="company_id">company_id</param>
		/// <returns>A collection SupplierProduct objects.</returns>
		public static EntityList<SupplierProduct> GetSupplierProductsBycompany_(int @company_id) 
		{
			string commandText = "SupplierProductGetByCompany";
			
			List<SqlParameter> parameters = new List<SqlParameter>();
			parameters.Add(new SqlParameter("@company_id", @company_id));
			
			return GetList<SupplierProduct>(commandText, parameters);
		}

		/// <summary>
		/// Create a new SupplierProduct object from a Company object.
		/// </summary>
		/// <param name="company_">company_</param>
		/// <returns>The newly created SupplierProduct object.</returns>
		public static SupplierProduct CreateSupplierProductBycompany_(Company @company_)
		{
			SupplierProduct supplierProduct = InitializeNew<SupplierProduct>();
			
			supplierProduct.company_id = @company_.company_id;
			
			supplierProduct.company_ = @company_;
			
			return supplierProduct;
		}
		
		/// <summary>
		/// Deletes SupplierProduct objects by a Company object.
		/// </summary>
		/// <param name="company">company</param>
		public static void DeleteSupplierProductsBycompany_(Company company) 
		{
			string commandText = "SupplierProductDeleteByCompany";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@company_id", company.company_id));
			
			using (SqlHelper helper = new SqlHelper()) 
			{
				helper.Execute(commandText, CommandType.StoredProcedure, parameters);
			}
		}
		
		/// <summary>
		/// Deletes SupplierProduct objects by a Company unique identifier.
		/// </summary>
		/// <param name="company_id">company_id</param>
		public static void DeleteSupplierProductsBycompany_(int company_id) 
		{
			string commandText = "SupplierProductDeleteByCompany";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@company_id", company_id));
			
			using (SqlHelper helper = new SqlHelper()) 
			{
				helper.Execute(commandText, CommandType.StoredProcedure, parameters);
			}
		}
		#endregion
		
		#region Subclasses
		public static partial class SupplierProductProperties
		{
			public const string company_id = "company_id";
			public const string product_code = "product_code";
			public const string barcode = "barcode";
			public const string department = "department";
			public const string brand = "brand";
			public const string description = "description";
			public const string RRP = "RRP";
			public const string is_GST = "is_GST";
			public const string is_available = "is_available";
			public const string picture_url = "picture_url";
			public const string info_url = "info_url";
			public const string wholesale_price = "wholesale_price";
			public const string member_price = "member_price";
			public const string range1_min_quantity = "range1_min_quantity";
			public const string range1_price = "range1_price";
			public const string range2_min_quantity = "range2_min_quantity";
			public const string range2_price = "range2_price";
			public const string range3_min_quantity = "range3_min_quantity";
			public const string range3_price = "range3_price";
			public const string lastupdated_datetime = "lastupdated_datetime";
		}
		#endregion
	}
}
