/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 15/07/2012 3:36:27 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will NOT be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Data.SqlClient;
using System.Text;

using HealthStop.Business.Framework;

namespace HealthStop.Business
{
	/// <summary>
	/// This object represents the properties and methods of a PurchaseOrderItem.
	/// </summary>
	public partial class PurchaseOrderItem : EntityBase
	{
          public decimal total
          {
               get
               {
                    return (Convert.ToDecimal(this.quantity) * this.cost_price);
               }
          }
	}
}
