/****** Object:  Stored Procedure AdminInsert - Script Date: Friday, 10 August 2012 ******/
if exists (select * from sysobjects where id = object_id(N'[AdminInsert]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [AdminInsert]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO

/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 10/08/2012 7:48:55 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

CREATE PROCEDURE [AdminInsert]
	@first_name varchar(100),
	@last_name varchar(100),
	@email varchar(100),
	@phone varchar(100),
	@mobile varchar(100),
	@password_hash char(128),
	@is_active bit,
	@creation_datetime datetime
AS

DECLARE @table TABLE(
	[admin_id] int,
	[first_name] varchar(100),
	[last_name] varchar(100),
	[email] varchar(100),
	[phone] varchar(100),
	[mobile] varchar(100),
	[password_hash] char(128),
	[is_active] bit,
	[creation_datetime] datetime
);

INSERT INTO [dbo].[Admins] (
	[Admins].[first_name],
	[Admins].[last_name],
	[Admins].[email],
	[Admins].[phone],
	[Admins].[mobile],
	[Admins].[password_hash],
	[Admins].[is_active],
	[Admins].[creation_datetime]
) 
output 
	INSERTED.[admin_id],
	INSERTED.[first_name],
	INSERTED.[last_name],
	INSERTED.[email],
	INSERTED.[phone],
	INSERTED.[mobile],
	INSERTED.[password_hash],
	INSERTED.[is_active],
	INSERTED.[creation_datetime]
into @table
VALUES ( 
	@first_name,
	@last_name,
	@email,
	@phone,
	@mobile,
	@password_hash,
	@is_active,
	@creation_datetime 
); 

SELECT 
	[admin_id],
	[first_name],
	[last_name],
	[email],
	[phone],
	[mobile],
	[password_hash],
	[is_active],
	[creation_datetime] 
FROM @table;


GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO



