/****** Object:  Stored Procedure AllowedStoreGetAll - Script Date: Friday, 10 August 2012 ******/
if exists (select * from sysobjects where id = object_id(N'[AllowedStoreGetAll]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [AllowedStoreGetAll]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO

/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 10/08/2012 7:48:56 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

CREATE PROCEDURE [AllowedStoreGetAll]

AS

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT 	[AllowedStores].[entry_id],
	[AllowedStores].[customer_id],
	[AllowedStores].[supplier_id],
	[AllowedStores].[account_number],
	[AllowedStores].[is_member],
	[AllowedStores].[authoriser_email],
	[AllowedStores].[creation_datetime] 
FROM [dbo].[AllowedStores]

GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO
