/****** Object:  Stored Procedure AllowedStoreInsert - Script Date: Friday, 10 August 2012 ******/
if exists (select * from sysobjects where id = object_id(N'[AllowedStoreInsert]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [AllowedStoreInsert]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO

/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 10/08/2012 7:48:56 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

CREATE PROCEDURE [AllowedStoreInsert]
	@customer_id int,
	@supplier_id int,
	@account_number varchar(100),
	@is_member bit,
	@authoriser_email varchar(100),
	@creation_datetime datetime
AS

DECLARE @table TABLE(
	[entry_id] int,
	[customer_id] int,
	[supplier_id] int,
	[account_number] varchar(100),
	[is_member] bit,
	[authoriser_email] varchar(100),
	[creation_datetime] datetime
);

INSERT INTO [dbo].[AllowedStores] (
	[AllowedStores].[customer_id],
	[AllowedStores].[supplier_id],
	[AllowedStores].[account_number],
	[AllowedStores].[is_member],
	[AllowedStores].[authoriser_email],
	[AllowedStores].[creation_datetime]
) 
output 
	INSERTED.[entry_id],
	INSERTED.[customer_id],
	INSERTED.[supplier_id],
	INSERTED.[account_number],
	INSERTED.[is_member],
	INSERTED.[authoriser_email],
	INSERTED.[creation_datetime]
into @table
VALUES ( 
	@customer_id,
	@supplier_id,
	@account_number,
	@is_member,
	@authoriser_email,
	@creation_datetime 
); 

SELECT 
	[entry_id],
	[customer_id],
	[supplier_id],
	[account_number],
	[is_member],
	[authoriser_email],
	[creation_datetime] 
FROM @table;


GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO



