/****** Object:  Stored Procedure CompanyUpdate - Script Date: Friday, 10 August 2012 ******/
if exists (select * from sysobjects where id = object_id(N'[CompanyUpdate]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [CompanyUpdate]
GO


SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO

/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 10/08/2012 7:48:58 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

CREATE PROCEDURE [CompanyUpdate]
	@company_id int,
	@name varchar(100),
	@brand_name varchar(100),
	@company_number varchar(20),
	@contact_name varchar(100),
	@contact_email varchar(100),
	@transactions_email varchar(100),
	@address varchar(100),
	@suburb varchar(100),
	@state varchar(100),
	@country varchar(100),
	@postcode varchar(100),
	@phone varchar(100),
	@website varchar(100),
	@api_key varchar(100),
	@notes varchar(8000),
	@is_active bit,
	@is_customer bit,
	@is_supplier bit,
	@is_manufacturer bit,
	@paidto_datetime datetime,
	@creation_datetime datetime,
	@has_POSSystem bit
AS

DECLARE @table TABLE(
	[company_id] int,
	[name] varchar(100),
	[brand_name] varchar(100),
	[company_number] varchar(20),
	[contact_name] varchar(100),
	[contact_email] varchar(100),
	[transactions_email] varchar(100),
	[address] varchar(100),
	[suburb] varchar(100),
	[state] varchar(100),
	[country] varchar(100),
	[postcode] varchar(100),
	[phone] varchar(100),
	[website] varchar(100),
	[api_key] varchar(100),
	[notes] varchar(8000),
	[is_active] bit,
	[is_customer] bit,
	[is_supplier] bit,
	[is_manufacturer] bit,
	[paidto_datetime] datetime,
	[creation_datetime] datetime,
	[has_POSSystem] bit
);

UPDATE [dbo].[Companies] SET 
	[Companies].[name] = @name,
	[Companies].[brand_name] = @brand_name,
	[Companies].[company_number] = @company_number,
	[Companies].[contact_name] = @contact_name,
	[Companies].[contact_email] = @contact_email,
	[Companies].[transactions_email] = @transactions_email,
	[Companies].[address] = @address,
	[Companies].[suburb] = @suburb,
	[Companies].[state] = @state,
	[Companies].[country] = @country,
	[Companies].[postcode] = @postcode,
	[Companies].[phone] = @phone,
	[Companies].[website] = @website,
	[Companies].[api_key] = @api_key,
	[Companies].[notes] = @notes,
	[Companies].[is_active] = @is_active,
	[Companies].[is_customer] = @is_customer,
	[Companies].[is_supplier] = @is_supplier,
	[Companies].[is_manufacturer] = @is_manufacturer,
	[Companies].[paidto_datetime] = @paidto_datetime,
	[Companies].[creation_datetime] = @creation_datetime,
	[Companies].[has_POSSystem] = @has_POSSystem 
output 
	INSERTED.[company_id],
	INSERTED.[name],
	INSERTED.[brand_name],
	INSERTED.[company_number],
	INSERTED.[contact_name],
	INSERTED.[contact_email],
	INSERTED.[transactions_email],
	INSERTED.[address],
	INSERTED.[suburb],
	INSERTED.[state],
	INSERTED.[country],
	INSERTED.[postcode],
	INSERTED.[phone],
	INSERTED.[website],
	INSERTED.[api_key],
	INSERTED.[notes],
	INSERTED.[is_active],
	INSERTED.[is_customer],
	INSERTED.[is_supplier],
	INSERTED.[is_manufacturer],
	INSERTED.[paidto_datetime],
	INSERTED.[creation_datetime],
	INSERTED.[has_POSSystem]
into @table
WHERE 
	[Companies].[company_id] = @company_id

SELECT 
	[company_id],
	[name],
	[brand_name],
	[company_number],
	[contact_name],
	[contact_email],
	[transactions_email],
	[address],
	[suburb],
	[state],
	[country],
	[postcode],
	[phone],
	[website],
	[api_key],
	[notes],
	[is_active],
	[is_customer],
	[is_supplier],
	[is_manufacturer],
	[paidto_datetime],
	[creation_datetime],
	[has_POSSystem] 
FROM @table;


GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO


