/****** Object:  Stored Procedure InvoiceInsert - Script Date: Friday, 10 August 2012 ******/
if exists (select * from sysobjects where id = object_id(N'[InvoiceInsert]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [InvoiceInsert]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO

/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 10/08/2012 7:49:01 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

CREATE PROCEDURE [InvoiceInsert]
	@customer_id int,
	@supplier_id int,
	@purchaseorder_id int,
	@freight money,
	@total money,
	@tax money,
	@is_downloaded bit,
	@creation_datetime datetime,
	@local_code varchar(100),
	@downloaded_datetime datetime
AS

DECLARE @table TABLE(
	[invoice_id] int,
	[customer_id] int,
	[supplier_id] int,
	[purchaseorder_id] int,
	[freight] money,
	[total] money,
	[tax] money,
	[is_downloaded] bit,
	[creation_datetime] datetime,
	[local_code] varchar(100),
	[downloaded_datetime] datetime
);

INSERT INTO [dbo].[Invoices] (
	[Invoices].[customer_id],
	[Invoices].[supplier_id],
	[Invoices].[purchaseorder_id],
	[Invoices].[freight],
	[Invoices].[total],
	[Invoices].[tax],
	[Invoices].[is_downloaded],
	[Invoices].[creation_datetime],
	[Invoices].[local_code],
	[Invoices].[downloaded_datetime]
) 
output 
	INSERTED.[invoice_id],
	INSERTED.[customer_id],
	INSERTED.[supplier_id],
	INSERTED.[purchaseorder_id],
	INSERTED.[freight],
	INSERTED.[total],
	INSERTED.[tax],
	INSERTED.[is_downloaded],
	INSERTED.[creation_datetime],
	INSERTED.[local_code],
	INSERTED.[downloaded_datetime]
into @table
VALUES ( 
	@customer_id,
	@supplier_id,
	@purchaseorder_id,
	@freight,
	@total,
	@tax,
	@is_downloaded,
	@creation_datetime,
	@local_code,
	@downloaded_datetime 
); 

SELECT 
	[invoice_id],
	[customer_id],
	[supplier_id],
	[purchaseorder_id],
	[freight],
	[total],
	[tax],
	[is_downloaded],
	[creation_datetime],
	[local_code],
	[downloaded_datetime] 
FROM @table;


GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO



