/****** Object:  Stored Procedure InvoiceItemInsert - Script Date: Friday, 10 August 2012 ******/
if exists (select * from sysobjects where id = object_id(N'[InvoiceItemInsert]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [InvoiceItemInsert]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO

/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 10/08/2012 7:49:00 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

CREATE PROCEDURE [InvoiceItemInsert]
	@invoice_id int,
	@product_code varchar(100),
	@barcode varchar(100),
	@description varchar(100),
	@quantity float,
	@cost_price money,
	@RRP money,
	@is_GST bit
AS

DECLARE @table TABLE(
	[invoice_id] int,
	[product_code] varchar(100),
	[barcode] varchar(100),
	[description] varchar(100),
	[quantity] float,
	[cost_price] money,
	[RRP] money,
	[is_GST] bit
);

INSERT INTO [dbo].[InvoiceItems] (
	[InvoiceItems].[invoice_id],
	[InvoiceItems].[product_code],
	[InvoiceItems].[barcode],
	[InvoiceItems].[description],
	[InvoiceItems].[quantity],
	[InvoiceItems].[cost_price],
	[InvoiceItems].[RRP],
	[InvoiceItems].[is_GST]
) 
output 
	INSERTED.[invoice_id],
	INSERTED.[product_code],
	INSERTED.[barcode],
	INSERTED.[description],
	INSERTED.[quantity],
	INSERTED.[cost_price],
	INSERTED.[RRP],
	INSERTED.[is_GST]
into @table
VALUES ( 
	@invoice_id,
	@product_code,
	@barcode,
	@description,
	@quantity,
	@cost_price,
	@RRP,
	@is_GST 
); 

SELECT 
	[invoice_id],
	[product_code],
	[barcode],
	[description],
	[quantity],
	[cost_price],
	[RRP],
	[is_GST] 
FROM @table;


GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO



