/****** Object:  Stored Procedure ManufacturerProductGet - Script Date: Friday, 10 August 2012 ******/
if exists (select * from sysobjects where id = object_id(N'[ManufacturerProductGet]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [ManufacturerProductGet]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO

/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 10/08/2012 7:49:02 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

CREATE PROCEDURE [ManufacturerProductGet]
	@company_id int,
	@product_code varchar(100)
AS

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT 
	[ManufacturerProducts].[company_id],
	[ManufacturerProducts].[product_code],
	[ManufacturerProducts].[barcode],
	[ManufacturerProducts].[department],
	[ManufacturerProducts].[description],
	[ManufacturerProducts].[picture_url],
	[ManufacturerProducts].[info_url],
	[ManufacturerProducts].[lastupdated_datetime] 
FROM [dbo].[ManufacturerProducts] 
WHERE 
	[ManufacturerProducts].[company_id] = @company_id
	AND [ManufacturerProducts].[product_code] = @product_code

GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO
