/****** Object:  Stored Procedure ManufacturerProductInsert - Script Date: Friday, 10 August 2012 ******/
if exists (select * from sysobjects where id = object_id(N'[ManufacturerProductInsert]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [ManufacturerProductInsert]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO

/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 10/08/2012 7:49:02 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

CREATE PROCEDURE [ManufacturerProductInsert]
	@company_id int,
	@product_code varchar(100),
	@barcode varchar(100),
	@department varchar(100),
	@description varchar(100),
	@picture_url varchar(300),
	@info_url varchar(300),
	@lastupdated_datetime datetime
AS

DECLARE @table TABLE(
	[company_id] int,
	[product_code] varchar(100),
	[barcode] varchar(100),
	[department] varchar(100),
	[description] varchar(100),
	[picture_url] varchar(300),
	[info_url] varchar(300),
	[lastupdated_datetime] datetime
);

INSERT INTO [dbo].[ManufacturerProducts] (
	[ManufacturerProducts].[company_id],
	[ManufacturerProducts].[product_code],
	[ManufacturerProducts].[barcode],
	[ManufacturerProducts].[department],
	[ManufacturerProducts].[description],
	[ManufacturerProducts].[picture_url],
	[ManufacturerProducts].[info_url],
	[ManufacturerProducts].[lastupdated_datetime]
) 
output 
	INSERTED.[company_id],
	INSERTED.[product_code],
	INSERTED.[barcode],
	INSERTED.[department],
	INSERTED.[description],
	INSERTED.[picture_url],
	INSERTED.[info_url],
	INSERTED.[lastupdated_datetime]
into @table
VALUES ( 
	@company_id,
	@product_code,
	@barcode,
	@department,
	@description,
	@picture_url,
	@info_url,
	@lastupdated_datetime 
); 

SELECT 
	[company_id],
	[product_code],
	[barcode],
	[department],
	[description],
	[picture_url],
	[info_url],
	[lastupdated_datetime] 
FROM @table;


GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO



