/****** Object:  Stored Procedure ManufacturerProductGetAll - Script Date: Friday, 10 August 2012 ******/
if exists (select * from sysobjects where id = object_id(N'[ManufacturerProductGetAll]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [ManufacturerProductGetAll]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO

/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 10/08/2012 7:49:02 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

CREATE PROCEDURE [ManufacturerProductGetAll]

AS

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT 	[ManufacturerProducts].[company_id],
	[ManufacturerProducts].[product_code],
	[ManufacturerProducts].[barcode],
	[ManufacturerProducts].[department],
	[ManufacturerProducts].[description],
	[ManufacturerProducts].[picture_url],
	[ManufacturerProducts].[info_url],
	[ManufacturerProducts].[lastupdated_datetime] 
FROM [dbo].[ManufacturerProducts]

GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO
