/****** Object:  Stored Procedure PermissionUpdate - Script Date: Friday, 10 August 2012 ******/
if exists (select * from sysobjects where id = object_id(N'[PermissionUpdate]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [PermissionUpdate]
GO


SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO

/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 10/08/2012 7:49:03 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

CREATE PROCEDURE [PermissionUpdate]
	@permission_id int,
	@role_name varchar(100),
	@admin_id int,
	@company_id int,
	@authoriser_id int,
	@company_position varchar(100),
	@creation_datetime datetime
AS

DECLARE @table TABLE(
	[permission_id] int,
	[role_name] varchar(100),
	[admin_id] int,
	[company_id] int,
	[authoriser_id] int,
	[company_position] varchar(100),
	[creation_datetime] datetime
);

UPDATE [dbo].[Permissions] SET 
	[Permissions].[role_name] = @role_name,
	[Permissions].[admin_id] = @admin_id,
	[Permissions].[company_id] = @company_id,
	[Permissions].[authoriser_id] = @authoriser_id,
	[Permissions].[company_position] = @company_position,
	[Permissions].[creation_datetime] = @creation_datetime 
output 
	INSERTED.[permission_id],
	INSERTED.[role_name],
	INSERTED.[admin_id],
	INSERTED.[company_id],
	INSERTED.[authoriser_id],
	INSERTED.[company_position],
	INSERTED.[creation_datetime]
into @table
WHERE 
	[Permissions].[permission_id] = @permission_id

SELECT 
	[permission_id],
	[role_name],
	[admin_id],
	[company_id],
	[authoriser_id],
	[company_position],
	[creation_datetime] 
FROM @table;


GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO


