/****** Object:  Stored Procedure PurchaseOrderItemInsert - Script Date: Friday, 10 August 2012 ******/
if exists (select * from sysobjects where id = object_id(N'[PurchaseOrderItemInsert]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [PurchaseOrderItemInsert]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO

/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 10/08/2012 7:49:04 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

CREATE PROCEDURE [PurchaseOrderItemInsert]
	@purchaseorder_id int,
	@product_code varchar(100),
	@barcode varchar(100),
	@description varchar(100),
	@quantity float,
	@cost_price money
AS

DECLARE @table TABLE(
	[purchaseorder_id] int,
	[product_code] varchar(100),
	[barcode] varchar(100),
	[description] varchar(100),
	[quantity] float,
	[cost_price] money
);

INSERT INTO [dbo].[PurchaseOrderItems] (
	[PurchaseOrderItems].[purchaseorder_id],
	[PurchaseOrderItems].[product_code],
	[PurchaseOrderItems].[barcode],
	[PurchaseOrderItems].[description],
	[PurchaseOrderItems].[quantity],
	[PurchaseOrderItems].[cost_price]
) 
output 
	INSERTED.[purchaseorder_id],
	INSERTED.[product_code],
	INSERTED.[barcode],
	INSERTED.[description],
	INSERTED.[quantity],
	INSERTED.[cost_price]
into @table
VALUES ( 
	@purchaseorder_id,
	@product_code,
	@barcode,
	@description,
	@quantity,
	@cost_price 
); 

SELECT 
	[purchaseorder_id],
	[product_code],
	[barcode],
	[description],
	[quantity],
	[cost_price] 
FROM @table;


GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO



