/****** Object:  Stored Procedure RoleInsert - Script Date: Friday, 10 August 2012 ******/
if exists (select * from sysobjects where id = object_id(N'[RoleInsert]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [RoleInsert]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO

/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 10/08/2012 7:49:05 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

CREATE PROCEDURE [RoleInsert]
	@role_name varchar(100),
	@notes varchar(100)
AS

DECLARE @table TABLE(
	[role_name] varchar(100),
	[notes] varchar(100)
);

INSERT INTO [dbo].[Roles] (
	[Roles].[role_name],
	[Roles].[notes]
) 
output 
	INSERTED.[role_name],
	INSERTED.[notes]
into @table
VALUES ( 
	@role_name,
	@notes 
); 

SELECT 
	[role_name],
	[notes] 
FROM @table;


GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO



