/****** Object:  Stored Procedure SupplierProductInsert - Script Date: Friday, 10 August 2012 ******/
if exists (select * from sysobjects where id = object_id(N'[SupplierProductInsert]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [SupplierProductInsert]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO

/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 10/08/2012 7:49:07 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

CREATE PROCEDURE [SupplierProductInsert]
	@company_id int,
	@product_code varchar(100),
	@barcode varchar(100),
	@department varchar(100),
	@brand varchar(100),
	@description varchar(100),
	@RRP money,
	@is_GST bit,
	@is_available bit,
	@picture_url varchar(300),
	@info_url varchar(300),
	@wholesale_price money,
	@member_price money,
	@range1_min_quantity float,
	@range1_price money,
	@range2_min_quantity float,
	@range2_price money,
	@range3_min_quantity float,
	@range3_price money,
	@lastupdated_datetime datetime
AS

DECLARE @table TABLE(
	[company_id] int,
	[product_code] varchar(100),
	[barcode] varchar(100),
	[department] varchar(100),
	[brand] varchar(100),
	[description] varchar(100),
	[RRP] money,
	[is_GST] bit,
	[is_available] bit,
	[picture_url] varchar(300),
	[info_url] varchar(300),
	[wholesale_price] money,
	[member_price] money,
	[range1_min_quantity] float,
	[range1_price] money,
	[range2_min_quantity] float,
	[range2_price] money,
	[range3_min_quantity] float,
	[range3_price] money,
	[lastupdated_datetime] datetime
);

INSERT INTO [dbo].[SupplierProducts] (
	[SupplierProducts].[company_id],
	[SupplierProducts].[product_code],
	[SupplierProducts].[barcode],
	[SupplierProducts].[department],
	[SupplierProducts].[brand],
	[SupplierProducts].[description],
	[SupplierProducts].[RRP],
	[SupplierProducts].[is_GST],
	[SupplierProducts].[is_available],
	[SupplierProducts].[picture_url],
	[SupplierProducts].[info_url],
	[SupplierProducts].[wholesale_price],
	[SupplierProducts].[member_price],
	[SupplierProducts].[range1_min_quantity],
	[SupplierProducts].[range1_price],
	[SupplierProducts].[range2_min_quantity],
	[SupplierProducts].[range2_price],
	[SupplierProducts].[range3_min_quantity],
	[SupplierProducts].[range3_price],
	[SupplierProducts].[lastupdated_datetime]
) 
output 
	INSERTED.[company_id],
	INSERTED.[product_code],
	INSERTED.[barcode],
	INSERTED.[department],
	INSERTED.[brand],
	INSERTED.[description],
	INSERTED.[RRP],
	INSERTED.[is_GST],
	INSERTED.[is_available],
	INSERTED.[picture_url],
	INSERTED.[info_url],
	INSERTED.[wholesale_price],
	INSERTED.[member_price],
	INSERTED.[range1_min_quantity],
	INSERTED.[range1_price],
	INSERTED.[range2_min_quantity],
	INSERTED.[range2_price],
	INSERTED.[range3_min_quantity],
	INSERTED.[range3_price],
	INSERTED.[lastupdated_datetime]
into @table
VALUES ( 
	@company_id,
	@product_code,
	@barcode,
	@department,
	@brand,
	@description,
	@RRP,
	@is_GST,
	@is_available,
	@picture_url,
	@info_url,
	@wholesale_price,
	@member_price,
	@range1_min_quantity,
	@range1_price,
	@range2_min_quantity,
	@range2_price,
	@range3_min_quantity,
	@range3_price,
	@lastupdated_datetime 
); 

SELECT 
	[company_id],
	[product_code],
	[barcode],
	[department],
	[brand],
	[description],
	[RRP],
	[is_GST],
	[is_available],
	[picture_url],
	[info_url],
	[wholesale_price],
	[member_price],
	[range1_min_quantity],
	[range1_price],
	[range2_min_quantity],
	[range2_price],
	[range3_min_quantity],
	[range3_price],
	[lastupdated_datetime] 
FROM @table;


GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO



